#ifndef _FRIEND_TYPE_H_
#define _FRIEND_TYPE_H_

#include "SystemTypes.h"

#define FRIEND_MAX_LIST_COUNT 		20
#define FRIEND_MAX_WAIT_LIST_COUNT 	50

enum FriendReqToAddResultCode
{
	FRIEND_REQ_TO_ADD_RESULT_CODE_SUCCESS,								// 추가 요청 성공
	FRIEND_REQ_TO_ADD_RESULT_CODE_CAN_NOT_ADD_SELF,						// 자기 자신은 추가할 수 없음
	FRIEND_REQ_TO_ADD_RESULT_CODE_EXCEED_MAX_LIST_COUNT_BY_SELF,		// 자신의 친구 최대 등록 개수 초과 
	FRIEND_REQ_TO_ADD_RESULT_CODE_EXCEED_MAX_LIST_COUNT_BY_OTHER,		// 상대방의 친구 최대 등록 개수 초과
	FRIEND_REQ_TO_ADD_RESULT_CODE_EXCEED_MAX_WAITLIST_COUNT_BY_OTHER,	// 상대방의 친구 최대 대기 목록 개수 초과
	FRIEND_REQ_TO_ADD_RESULT_CODE_ALREADY_EXIST_FRIEND_IN_WAIT_LIST,	// 이미 대기목록에 존재함 
	FRIEND_REQ_TO_ADD_RESULT_CODE_ALREADY_EXIST_FRIEND,					// 이미 추가된 친구
	FRIEND_REQ_TO_ADD_RESULT_CODE_NOT_EXIST_NAME,						// 존재하지 않는 이름임
	FRIEND_REQ_TO_ADD_RESULT_CODE_DIFFERENT_RACE,						// 서로 다른 종족임
	FRIEND_REQ_TO_ADD_RESULT_CODE_DENY_ADD_REQUEST,						// 친구 추가 요청을 거부함
	
	FRIEND_REQ_TO_ADD_RESULT_CODE_MAX
};

enum FriendResToAddResultCode
{ 
	FRIEND_RES_TO_ADD_RESULT_CODE_SUCCESS,								// 수락 요청 성공
	FRIEND_RES_TO_ADD_RESULT_CODE_EXCEED_NOT_EXIST_IN_WAITLIST,			// 대기 목록에 존재하지 않음
	FRIEND_RES_TO_ADD_RESULT_CODE_EXCEED_MAX_LIST_COUNT_BY_SELF,		// 자신의 친구 최대 등록 개수 초과
	FRIEND_RES_TO_ADD_RESULT_CODE_EXCEED_MAX_LIST_COUNT_BY_OTHER,		// 상대방의 친구 최대 등록 개수 초과

	FRIEND_RES_TO_ADD_RESULT_CODE_MAX
};

// 친구 추가 요청 에 대한 수락 코드
enum FriendAddResponseCode
{
	FRIEND_ADD_RESPONSE_CODE_REJECT = 0,
	FRIEND_ADD_RESPONSE_CODE_ACCEPT = 1,
	
	FRIEND_ADD_RESPONSE_MAX
};

#endif
