#ifndef __PACKETITEMDEF_H__
#define __PACKETITEMDEF_H__

enum HelmetType { 
	HELMET_NONE , 
	HELMET1 ,
	HELMET2 ,
	HELMET3 ,
	HELMET4 ,	//by viva 171
	HELMET5 ,	//181
	HELMET6 ,
	HELMET7 ,   //231
	HELMET_MAX
};

enum JacketType { 
	JACKET_BASIC , 
	JACKET1 , 
	JACKET2 ,
	JACKET3 ,
	JACKET4 ,
	JACKET5 , //by viva 171
	JACKET6	, //181
	JACKET7	,
	JACKET8	,//231
	JACKET_MAX
};

enum PantsType { 
	PANTS_BASIC , 
	PANTS1 , 
	PANTS2 ,
	PANTS3 ,
	PANTS4 ,
	PANTS5 ,
	PANTS6 ,
	PANTS_MAX
};


enum WeaponType { 
	WEAPON_NONE ,
	WEAPON_SWORD ,
	WEAPON_SWORD_2 ,	//by viva 171 181
	//WEAPON_SWORD_3 ,
	WEAPON_BLADE ,
	WEAPON_BLADE_2 ,
//	WEAPON_BLADE_3 ,
	WEAPON_SR ,
	WEAPON_SR_2 ,
//	WEAPON_SR_3 ,
	WEAPON_AR ,
	WEAPON_AR_2 ,
//	WEAPON_AR_3 ,
	WEAPON_SG ,
	WEAPON_SMG ,
	WEAPON_CROSS ,
	WEAPON_CROSS_2 ,
//	WEAPON_CROSS_3 ,
	WEAPON_MACE ,
	WEAPON_MACE_2 ,
//	WEAPON_MACE_3 ,
	WEAPON_MAX
//	WEAPON_SHIELD ,
//	WEAPON_SWORD_SHIELD ,
};

enum ShieldType { 
	SHIELD_NONE ,
	SHIELD1 ,
	SHIELD2 ,
	SHIELD3 ,	//by viva 171
	SHIELD4 ,	//181
	SHIELD5 ,
	SHIELD6 ,//231
	SHIELD_MAX
};

enum MotorcycleType {
	MOTORCYCLE_NONE ,
	MOTORCYCLE1 ,
	MOTORCYCLE2 ,
	MOTORCYCLE3 ,
	MOTORCYCLE4 ,
	MOTORCYCLE5 ,
	MOTORCYCLE6 ,
	MOTORCYCLE7 ,
	MOTORCYCLE_MAX
};

enum ShoulderType{
	SHOULDER_NONE ,
	SHOULDER1 ,
	SHOULDER_MAX
};

enum VampireCoatType 
{ 
	VAMPIRE_COAT_BASIC , 
	VAMPIRE_COAT1 , 
	VAMPIRE_COAT2 ,
	VAMPIRE_COAT3 ,
	VAMPIRE_COAT4 ,
	VAMPIRE_COAT5 ,	//by viva 171
	VAMPIRE_COAT6 ,	//181
	VAMPIRE_COAT7 ,
	VAMPIRE_COAT8 ,//231
	VAMPIRE_COAT_MAX
};

enum VampireArmType
{
	VAMPIRE_ARM_NONE,
	VAMPIRE_ARM_WEAPON,
	VAMPIRE_ARM_WEAPON2, //by viva 171
	VAMPIRE_ARM_WEAPON3, //181
	VAMPIRE_ARM_WEAPON4,
	VAMPIRE_ARM_WEAPON5,//231
	VAMPIRE_ARM_MAX
};

enum OustersCoatType 
{ 
	OUSTERS_COAT_BASIC , 
	OUSTERS_COAT1 , 
	OUSTERS_COAT2 ,
	OUSTERS_COAT3 ,
	OUSTERS_COAT4 ,
	OUSTERS_COAT5 ,	//by viva 171
	OUSTERS_COAT6 ,	//181
	OUSTERS_COAT7 ,	//by rallser201
	OUSTERS_COAT8 ,//231
	OUSTERS_COAT_MAX
};

enum OustersArmType
{
	OUSTERS_ARM_GAUNTLET,
	OUSTERS_ARM_CHAKRAM,
	OUSTERS_ARM_CHAKRAM_171,	//by viva 171
	OUSTERS_ARM_CHAKRAM_181,	//181
	OUSTERS_ARM_CHAKRAM_201,	//by rallser201
	OUSTERS_ARM_CHAKRAM_231,
	OUSTERS_ARM_MAX
};

enum OustersSylphType
{
	OUSTERS_SYLPH_OFF,
	OUSTERS_SYLPH_ON,
	OUSTERS_SYLPH_MAX
};


#endif
