#include "StdAfx.h"
#include <fstream>
#include <mmsystem.h>

// def
#include "MTypeDef.h"
#include "MFileDef.h"
#include "AddonDef.h"
#include "SoundDef.h"
#include "EffectSpriteTypeDef.h"

// table
#include "ClientConfig.h"
#include "UserOption.h"
#include "MSoundTable.h"
#include "MMusicTable.h"
#include "MZoneTable.h"
#include "MItemTable.h"
#include "MItemOptionTable.h"
#include "MInteractionObjectTable.h"
#include "CFileIndexTable.h"
#include "MCreatureTable.h"
#include "MCreatureSpriteTable.h"
#include "CFramePack.h"
#include "MShopTemplateTable.h"
#include "MNPCTable.h"
#include "MEffectSpriteTypeTable.h"
#include "MEffectStatusTable.h"
#include "MActionInfoTable.h"
#include "MGameStringTable.h"
#include "MServerItemTable.h"
#include "MSkillManager.h"
#include "MEffectGeneratorDef.h"
#include "MusicDef.h"
#include "MChatManager.h"
#include "MLevelNameTable.h"
#include "AppendPatchInfo.h"
#include "AddonDef.h"
#include "RankBonusTable.h"
#include "ServerRankBonusTable.h"
#include "windows.h"
#include "MMinMaxInfo.h"
#include "packet/Properties.h"
#include "MItem.h"

#include "Packet\types\PacketItemDef.h"
#include "MathTable.h"

#define SAVE_TO_FILE

HRESULT InitFail(LPCTSTR szError,...);
bool 
FileOpenBinary(const char* filename, ivfstream& file);
//---------------------------------------------------------------------------
// Open File
//---------------------------------------------------------------------------
bool 
FileCheck(const char* filename);

BOOL	InitActionInfoTableFireCracker( int *FrameSize)
{
	// SKILL_FIRE_CRACKER_1, 气磷
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1].Set("SKILL_FIRE_CRACKER_1", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_1];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_1][1].SoundID				= SOUND_ITEM_BOOM3;

	// SKILL_FIRE_CRACKER_2, 气磷
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2].Set("SKILL_FIRE_CRACKER_2", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_2;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_2][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW;

	// SKILL_FIRE_CRACKER_3,气磷
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3].Set("SKILL_FIRE_CRACKER_3", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_3];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_3][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW;

	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER].Set("SKILL_DRAGON_FIRE_CRACKER", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER].Init( 5 );
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][0].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][0].EffectSpriteType	= EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][0].Count				= FrameSize[EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER];
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][0].SoundID				= SOUND_DRAGON_FIRE_CRACKER;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][0].LinkCount			= 0;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][1].EffectSpriteType	= EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER_FRONT;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][1].Count				= FrameSize[EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER_FRONT];
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][1].LinkCount			= 0;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][2].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][2].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][2].Count				= 12;//rameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][2].Step					= 30;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][2].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][3].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][3].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_1;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][3].Step				= 0;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][3].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_1];
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][3].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][3].LinkCount			= 10; // l
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][4].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][4].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_1;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][4].Step				= 30;
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][4].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_1];
	(*g_pActionInfoTable)[SKILL_DRAGON_FIRE_CRACKER][4].SoundID				= SOUND_ITEM_BOOM3;

	// SKILL_FIRE_CRACKER_3,气磷
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4].Set("SKILL_FIRE_CRACKER_4", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_4;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_4];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_4][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1].Set("SKILL_FIRE_CRACKER_VOLLEY_1", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_1];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_1][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW

	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2].Set("SKILL_FIRE_CRACKER_VOLLEY_2", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_2;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_2][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW

	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3].Set("SKILL_FIRE_CRACKER_VOLLEY_3", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_3];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_3][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW

	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4].Set("SKILL_FIRE_CRACKER_VOLLEY_4", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4].Init( 2 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][0].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_4;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][1].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_4];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_VOLLEY_4][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW

	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1].Set("SKILL_FIRE_CRACKER_WIDE_VOLLEY_1", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1].Init( 3 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][0].Step					= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][1].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_1];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][1].LinkCount			= 10; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][2].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][2].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][2].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][2].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_1];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_1][2].SoundID				= SOUND_ITEM_BOOM3;


	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2].Set("SKILL_FIRE_CRACKER_WIDE_VOLLEY_2", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2].Init( 3 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][0].Step					= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_2;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][1].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][1].LinkCount			= 10; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][2].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][2].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_2;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][2].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][2].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_2][2].SoundID				= SOUND_ITEM_BOOM3;


	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3].Set("SKILL_FIRE_CRACKER_WIDE_VOLLEY_3", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3].Init( 3 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][0].Step					= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][1].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_3];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][1].LinkCount			= 10; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][2].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][2].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][2].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][2].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_3];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_3][2].SoundID				= SOUND_ITEM_BOOM3;


	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4].Set("SKILL_FIRE_CRACKER_WIDE_VOLLEY_4", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4].Init( 3 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][0].Step					= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_4;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][1].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_4];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][1].LinkCount			= 10; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][2].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][2].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_4;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][2].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][2].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_4];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_WIDE_VOLLEY_4][2].SoundID				= SOUND_ITEM_BOOM3;

	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM].Set("SKILL_FIRE_CRACKER_STORM", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM].SetSoundID( SOUNDID_NULL );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM].SetStartWithCasting();
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM].Init( 9 );
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][0].EffectGeneratorID	= EFFECTGENERATORID_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][0].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_RISING;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][0].Step					= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][0].Count				= 9;//FrameSize[EFFECTSPRITETYPE_CURE_ALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][0].SoundID				= SOUND_SLAYER_ATTACK_MELEE;//SOUND_SLAYER_HEALING_CCW;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][1].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][1].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][1].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][1].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_1];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][1].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][1].LinkCount			= 4; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][2].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][2].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_2;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][2].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][2].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][2].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][2].LinkCount			= 3; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][3].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][3].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][3].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][3].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_3];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][3].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][3].LinkCount			= 5; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][4].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][4].EffectSpriteType	= EFFECTSPRITETYPE_FIRE_CRACKER_4;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][4].Step				= 0;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][4].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_4];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][4].SoundID				= SOUND_ITEM_BOOM3;//SOUND_SLAYER_HEALING_CCW
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][4].LinkCount			= 2; // l
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][5].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][5].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][5].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][5].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_1];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][5].SoundID				= SOUND_ITEM_BOOM3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][5].LinkCount			= 1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][6].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][6].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_2;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][6].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][6].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_2];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][6].SoundID				= SOUND_ITEM_BOOM3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][6].LinkCount			= 1;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][7].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][7].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][7].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][7].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_3];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][7].SoundID				= SOUND_ITEM_BOOM3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][7].LinkCount			= 3;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][8].EffectGeneratorID	= EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][8].EffectSpriteType = EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_4;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][8].Step				= 30;
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][8].Count				= FrameSize[EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_4];
	(*g_pActionInfoTable)[SKILL_FIRE_CRACKER_STORM][8].SoundID				= SOUND_ITEM_BOOM3;

	(*g_pActionInfoTable)[SKILL_MUTE].Set("MUTE", ACTION_STAND, EFFECTSPRITETYPE_NULL, 5, 5);
	(*g_pActionInfoTable)[SKILL_MUTE].SetSoundID( SOUNDID_NULL );

	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION].Set("REGEN_TOWER_TRING_POSITION", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION].Init( 1 );
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_ZONE;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION][0].EffectSpriteType = EFFECTSPRITETYPE_REGEN_TOWER_GROUND;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION][0].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION][0].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_GROUND];
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION][0].SetDelayNode();
	
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT].Set("REGEN_TOWER_THROW_LIGHT", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_SELF);
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT].Init( 3 );
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT].SetMainNode( 1 );
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][0].EffectSpriteType = EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_START;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][0].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][0].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_START];
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][0].LinkCount			= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_START];
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][1].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][1].EffectSpriteType = EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_ING;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][1].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][1].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_ING];
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][1].SoundID			= SOUND_REGEN_TOWER_REPEAT;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][1].SetDelayNode();
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][2].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][2].EffectSpriteType	= EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_END;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][2].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_THROW_LIGHT][2].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_END];

	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT].Set("REGEN_TOWER_TRING_POSITION_LIGHT", ACTION_STAND, EFFECTSPRITETYPE_NULL, 10, FLAG_ACTIONINFO_TARGET_ZONE);
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT].Init( 3 );
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT].SetMainNode( 1 );
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][0].EffectGeneratorID = EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][0].EffectSpriteType = EFFECTSPRITETYPE_REGEN_TOWER_GROUND_LIGHT_START;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][0].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][0].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_GROUND_LIGHT_START];
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][0].LinkCount			= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_GROUND_LIGHT_START];
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][1].EffectGeneratorID = EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][1].EffectSpriteType = EFFECTSPRITETYPE_REGEN_TOWER_GROUND_LIGHT_ING;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][1].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][1].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_GROUND_LIGHT_ING];
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][1].SetDelayNode();
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][2].EffectGeneratorID = EFFECTGENERATORID_STOP_ZONE;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][2].EffectSpriteType	= EFFECTSPRITETYPE_REGEN_TOWER_GROUND_LIGHT_END;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][2].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_TRING_POSITION_LIGHT][2].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_GROUND_LIGHT_END];

	(*g_pActionInfoTable)[REGEN_TOWER_FLASH_BEAD].Set("REGEN_TOWER_FLASH_BEAD", ACTION_STAND, EFFECTSPRITETYPE_NULL,10, FLAG_ACTIONINFO_TARGET_SELF );
	(*g_pActionInfoTable)[REGEN_TOWER_FLASH_BEAD].Init ( 1 );
	(*g_pActionInfoTable)[REGEN_TOWER_FLASH_BEAD][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[REGEN_TOWER_FLASH_BEAD][0].EffectSpriteType = EFFECTSPRITETYPE_REGEN_TOWER_RIGHT_BEAD;
	(*g_pActionInfoTable)[REGEN_TOWER_FLASH_BEAD][0].Step				= 30;
	(*g_pActionInfoTable)[REGEN_TOWER_FLASH_BEAD][0].Count				= FrameSize[EFFECTSPRITETYPE_REGEN_TOWER_RIGHT_BEAD];
	
	return TRUE;
}
