#include "StdAfx.h"
#include <fstream>

// def
#include "MTypeDef.h"
#include "MFileDef.h"
#include "AddonDef.h"
#include "SoundDef.h"
#include "EffectSpriteTypeDef.h"

// table
#include "ClientConfig.h"
#include "UserOption.h"
#include "MSoundTable.h"
#include "MMusicTable.h"
#include "MZoneTable.h"
#include "MItemTable.h"
#include "MItemOptionTable.h"
#include "MInteractionObjectTable.h"
#include "CFileIndexTable.h"
#include "MCreatureTable.h"
#include "MCreatureSpriteTable.h"
#include "CFramePack.h"
#include "MShopTemplateTable.h"
#include "MNPCTable.h"
#include "MEffectSpriteTypeTable.h"
#include "MEffectStatusTable.h"
#include "MActionInfoTable.h"
#include "MGameStringTable.h"
#include "MServerItemTable.h"
#include "MSkillManager.h"
#include "MEffectGeneratorDef.h"
#include "MusicDef.h"
#include "MChatManager.h"
#include "MLevelNameTable.h"
#include "AppendPatchInfo.h"
#include "AddonDef.h"
#include "RankBonusTable.h"
#include "ServerRankBonusTable.h"
#include "windows.h"
#include "MMinMaxInfo.h"
#include "packet/Properties.h"
#include "MItem.h"

#include "Packet\types\PacketItemDef.h"
#include "MathTable.h"

#define SAVE_TO_FILE

HRESULT InitFail(LPCTSTR szError,...);
bool 
FileOpenBinary(const char* filename, ivfstream& file);
//---------------------------------------------------------------------------
// Open File
//---------------------------------------------------------------------------
bool 
FileCheck(const char* filename);


BOOL	InitActionInfoTableOusters( CCreatureFramePack		&AddonFPK,CCreatureFramePack		&CreatureFPK ,int *FrameSize)
{
		(*g_pActionInfoTable)[RESULT_SKILL_FLOURISH].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_FLOURISH].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_EVADE].Set("SKILL_EVADE", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_SELF);
	(*g_pActionInfoTable)[SKILL_EVADE].SetSound( SOUNDID_NULL );

	// 적의 몸에 이펙트를 한번 붙인다.
    (*g_pActionInfoTable)[RESULT_SKILL_EVADE].Set("RESULT_SKILL_EVADE", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_EVADE].SetSound( SOUNDID_NULL );
	(*g_pActionInfoTable)[RESULT_SKILL_EVADE].Init( 1 );
	(*g_pActionInfoTable)[RESULT_SKILL_EVADE][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_EVADE][0].EffectSpriteType  = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_EVADE][0].Step				= 30;
	(*g_pActionInfoTable)[RESULT_SKILL_EVADE][0].Count				= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_EVADE][0].SoundID			= SOUNDID_NULL;

	(*g_pActionInfoTable)[SKILL_SHARP_ROUND].Set("SKILL_SHARP_ROUND", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_SHARP_ROUND].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND].Set("RESULT_SKILL_SHARP_ROUND", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND].SetSound( SOUNDID_NULL );
	(*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND].Init( 1 );
	(*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND][0].EffectSpriteType = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND][0].Step			= 30;
	(*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND][0].Count		= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_SHARP_ROUND][0].SoundID		= SOUNDID_NULL;
	
	// HIDE_SIGHT 는 PASSIVE 기술
	(*g_pActionInfoTable)[SKILL_HIDE_SIGHT].Set("SKILL_HIDE_SIGHT", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_HIDE_SIGHT].SetSound( SOUNDID_NULL );
    (*g_pActionInfoTable)[RESULT_SKILL_HIDE_SIGHT].Set("RESULT_SKILL_HIDE_SIGHT", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_HIDE_SIGHT].SetSound( SOUNDID_NULL );
	
	(*g_pActionInfoTable)[SKILL_BACK_STEP].Set("SKILL_BACK_STEP", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_BACK_STEP].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP].Set("RESULT_SKILL_BACK_STEP", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP].SetSound( SOUNDID_NULL );
	(*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP].Init( 1 );
	(*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP][0].EffectSpriteType  = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP][0].Step				= 30;
	(*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP][0].Count				= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_BACK_STEP][0].SoundID			= SOUNDID_NULL;		

	(*g_pActionInfoTable)[SKILL_BLUNTING].Set("SKILL_BLUNTING", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_BLUNTING].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_BLUNTING].Set("RESULT_SKILL_BLUNTING", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_BLUNTING].SetSound( SOUNDID_NULL );
	(*g_pActionInfoTable)[RESULT_SKILL_BLUNTING][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_BLUNTING][0].EffectSpriteType  = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_BLUNTING][0].Step				= 30;
	(*g_pActionInfoTable)[RESULT_SKILL_BLUNTING][0].Count				= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_BLUNTING][0].SoundID				= SOUNDID_NULL;

	(*g_pActionInfoTable)[SKILL_GAMMA_CHOP].Set("SKILL_GAMMA_CHOP", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_GAMMA_CHOP].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP].Set("RESULT_SKILL_GAMMA_CHOP", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP].SetSound( SOUNDID_NULL );
	(*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP][0].Init( 1 );
	(*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP][0].EffectSpriteType = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP][0].Step				= 30;
	(*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP][0].Count				= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_GAMMA_CHOP][0].SoundID			= SOUNDID_NULL;

	(*g_pActionInfoTable)[SKILL_CROSS_GUARD].Set("SKILL_CROSS_GUARD", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_SELF);
	(*g_pActionInfoTable)[SKILL_CROSS_GUARD].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_CROSS_GUARD].Set("RESULT_SKILL_CROSS_GUARD", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_CROSS_GUARD].SetSound( SOUNDID_NULL );
	(*g_pActionInfoTable)[RESULT_SKILL_CROSS_GUARD][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_CROSS_GUARD][0].EffectSpriteType = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_CROSS_GUARD][0].Step				= 30;
	(*g_pActionInfoTable)[RESULT_SKILL_CROSS_GUARD][0].Count			= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_CROSS_GUARD][0].SoundID			= SOUNDID_NULL;

	(*g_pActionInfoTable)[SKILL_FIRE_OF_SOUL_STONE].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_FIRE_OF_SOUL_STONE].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_FIRE_OF_SOUL_STONE].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_FIRE_OF_SOUL_STONE].SetSound( SOUND_OUSTERS_FIRE_OF_SOUL_STONE );

	(*g_pActionInfoTable)[SKILL_ICE_OF_SOUL_STONE].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_ICE_OF_SOUL_STONE].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_ICE_OF_SOUL_STONE].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_ICE_OF_SOUL_STONE].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_SAND_OF_SOUL_STONE].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_SAND_OF_SOUL_STONE].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_SAND_OF_SOUL_STONE].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_SAND_OF_SOUL_STONE].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_BLOCK_HEAD].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_BLOCK_HEAD].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_BLOCK_HEAD].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_BLOCK_HEAD].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_KASAS_ARROW].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_KASAS_ARROW].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW].SetSound( SOUND_OUSTERS_KASA_S_ARROW );
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW].Init( 2 );
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][0].EffectGeneratorID = EFFECTGENERATORID_ATTACK_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][0].EffectSpriteType = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][0].Step				= 25;
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][0].Count			= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][0].SoundID			= SOUNDID_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][1].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][1].EffectSpriteType = EFFECTSPRITETYPE_NULL;
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][1].Step				= 25;
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][1].Count			= FrameSize[];
	(*g_pActionInfoTable)[RESULT_SKILL_KASAS_ARROW][1].SoundID			= SOUNDID_NULL;

	(*g_pActionInfoTable)[SKILL_HANDS_OF_FIRE].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_HANDS_OF_FIRE].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_HANDS_OF_FIRE].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_HANDS_OF_FIRE].SetSound( SOUNDID_NULL );
	(*g_pActionInfoTable)[RESULT_SKILL_HANDS_OF_FIRE].Init( 2 );
	(*g_pActionInfoTable)[RESULT_SKILL_HANDS_OF_FIRE][0].EffectGeneratorID = EFFECTGENERATORID_ATTACH_CREATURE;
	(*g_pActionInfoTable)[RESULT_SKILL_HANDS_OF_FIRE][0].EffectSpriteType = EFFECTSPRITETYPE_NULL;

	(*g_pActionInfoTable)[SKILL_PROMINENCE].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_PROMINENCE].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_PROMINENCE].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_PROMINENCE].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_RING_OF_FLARE].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_RING_OF_FLARE].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_RING_OF_FLARE].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_RING_OF_FLARE].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_BLAZE_BOLT].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_BLAZE_BOLT].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_BLAZE_BOLT].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_BLAZE_BOLT].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_ICE_FIELD].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_ICE_FIELD].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_ICE_FIELD].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_ICE_FIELD].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_WATER_BARRIER].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_WATER_BARRIER].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_WATER_BARRIER].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_WATER_BARRIER].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_HANDS_OF_NIZIE].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_HANDS_OF_NIZIE].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_HANDS_OF_NIZIE].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_HANDS_OF_NIZIE].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_NYMPH_RECOVERY].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_NYMPH_RECOVERY].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_NYMPH_RECOVERY].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_NYMPH_RECOVERY].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_LIBERTY].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_LIBERTY].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_LIBERTY].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_LIBERTY].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_TENDRIL].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_TENDRIL].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_TENDRIL].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_TENDRIL].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_GNOMES_WHISPER].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_GNOMES_WHISPER].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[RESULT_SKILL_GNOMES_WHISPER].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_GNOMES_WHISPER].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_STONE_AUGER].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_STONE_AUGER].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_STONE_AUGER].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_STONE_AUGER].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_REFUSAL_ETHER].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_REFUSAL_ETHER].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_REFUSAL_ETHER].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_REFUSAL_ETHER].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_REFUSAL_ETHER].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_REFUSAL_ETHER].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_EARTHS_TEETH].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_EARTHS_TEETH].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_EARTHS_TEETH].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_EARTHS_TEETH].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_ABSORB_SOUL].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_ABSORB_SOUL].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_ABSORB_SOUL].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_ABSORB_SOUL].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_SUMMON_SYLPH].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_SUMMON_SYLPH].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_SUMMON_SYLPH].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_SUMMON_SYLPH].SetSound( SOUNDID_NULL );


	(*g_pActionInfoTable)[SKILL_DRIFTING_SOUL].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_DRIFTING_SOUL].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_DRIFTING_SOUL].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_DRIFTING_SOUL].SetSound( SOUNDID_NULL );

	(*g_pActionInfoTable)[SKILL_CRITICAL_MAGIC].Set("SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[SKILL_CRITICAL_MAGIC].SetSound( SOUNDID_NULL );

    (*g_pActionInfoTable)[RESULT_SKILL_CRITICAL_MAGIC].Set("RESULT_SKILL_FLOURISH", ACTION_MAGIC, EFFECTSPRITETYPE_NULL, 5, FLAG_ACTIONINFO_TARGET_OTHER);
	(*g_pActionInfoTable)[RESULT_SKILL_CRITICAL_MAGIC].SetSound( SOUNDID_NULL );

}
