//---------------------------------------------------------------------------
// GameInitInfo.cpp
//---------------------------------------------------------------------------
// Information Table에 대한 초기화를 한다.
//---------------------------------------------------------------------------
//-----------------------------------------------------------------------------
// Include files
//-----------------------------------------------------------------------------
#include "StdAfx.h"
#include <fstream>
#include <mmsystem.h>

// def
#include "MTypeDef.h"
#include "MFileDef.h"
#include "AddonDef.h"
#include "SoundDef.h"
#include "EffectSpriteTypeDef.h"

// table
#include "ClientConfig.h"
#include "UserOption.h"
#include "MSoundTable.h"
#include "MMusicTable.h"
#include "MZoneTable.h"
#include "MItemTable.h"
#include "MItemOptionTable.h"
#include "MInteractionObjectTable.h"
#include "CFileIndexTable.h"
#include "MCreatureTable.h"
#include "MCreatureSpriteTable.h"
#include "CFramePack.h"
#include "MShopTemplateTable.h"
#include "MNPCTable.h"
#include "MEffectSpriteTypeTable.h"
#include "MEffectStatusTable.h"
#include "MActionInfoTable.h"
#include "MGameStringTable.h"
#include "MServerItemTable.h"
#include "MSkillManager.h"
#include "MEffectGeneratorDef.h"
#include "MusicDef.h"
#include "MChatManager.h"
#include "MLevelNameTable.h"
#include "AppendPatchInfo.h"
#include "AddonDef.h"
#include "RankBonusTable.h"
#include "ServerRankBonusTable.h"
#include "MMinMaxInfo.h"
#include "packet/Properties.h"
#include "MItem.h"

#include "Packet\types\PacketItemDef.h"
#include "MathTable.h"

//#ifdef OUTPUT_DEBUG
	#define SAVE_TO_FILE
//#endif


#define		FILE_INFO_SERVER_RANK_BONUS	"Data\\ServerRankBonus.inf"
#define		FILE_INFO_SERVER_ITEM		"Data\\ServerItemInfo.inf"
#define		FILE_INFO_SERVER_NPC		"Data\\ServerNPC.inf"

#define		FILE_INFO_CHAT_CURSE		"Data\\yok.txt"
#define		FILE_INFO_CHAT_CURSE_2		"Data\\yok2.txt"// 캐릭터 이름에서만 필터링 될 것들

#define		FILE_INFO_CHAT_CURSE_NET		"Data\\yok_net.txt"
#define		FILE_INFO_CHAT_CURSE_NET_2		"Data\\yok2_net.txt"

#define		COLOR_CHIEF_MAGE			44
#define		COLOR_CHIEF_FIGHT			120
#define		COLOR_CHIEF_MAGE_FIGHT		485


HRESULT InitFail(LPCTSTR szError,...);
bool 
FileOpenBinary(const char* filename, ivfstream& file);
//---------------------------------------------------------------------------
// Open File
//---------------------------------------------------------------------------
bool 
FileCheck(const char* filename);
BOOL	InitActionInfoTable( CCreatureFramePack		&AddonFPK,CCreatureFramePack		&CreatureFPK , CCreatureFramePack &OustersFPK, int *FrameSize);
BOOL	InitEffectStatusTable();
BOOL	InitZoneInfo();
BOOL	InitSoundTable();
BOOL	InitCreatureSpriteTable();
BOOL	InitCreatureTable();

//-----------------------------------------------------------------------------
// Limit Light
//-----------------------------------------------------------------------------
// 일부 effect는 밝기 filter 크기가 너무 커서 제한한다.
//-----------------------------------------------------------------------------
void LimitLight( CEffectFramePack& EFPK, int limit );
void InitScreenEffectLight(CEffectFramePack& ScreenEFPK);
void InitAlphaEffectLight(CEffectFramePack& EFPK);

void	InitEffectLight(CEffectFramePack& ScreenEFPK, CEffectFramePack& EFPK)
{
	InitScreenEffectLight(ScreenEFPK);
	InitAlphaEffectLight(EFPK);
}



void InitScreenEffectLight(CEffectFramePack& ScreenEFPK)
{
	int est;
	
	//---------------------------------------------------------------------
	// light 3개
	//---------------------------------------------------------------------
	int lightEffect = ScreenEFPK[EFFECTSPRITETYPE_LIGHT_2-MAX_EFFECTSPRITETYPE_ALPHAEFFECT][0][0].GetLight();
	
	//			const int numLight = 67 + 34;
	int estLight[] = {
		EFFECTSPRITETYPE_LIGHT_1,
			EFFECTSPRITETYPE_LIGHT_2,
			EFFECTSPRITETYPE_LIGHT_3,					
			EFFECTSPRITETYPE_MAP_LIGHT_YELLOW,
			EFFECTSPRITETYPE_MAP_LIGHT_RED,
			EFFECTSPRITETYPE_MAP_FIRE,
			EFFECTSPRITETYPE_FIRE_CRACKER_1,
			EFFECTSPRITETYPE_FIRE_CRACKER_2,
			EFFECTSPRITETYPE_FIRE_CRACKER_3,
			EFFECTSPRITETYPE_FIRE_CRACKER_4 ,					
			EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_1 , // 10
			EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_2 ,
			EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_3 ,
			EFFECTSPRITETYPE_FIRE_CRACKER_SMALL_4 ,					
			EFFECTSPRITETYPE_GREGORI,					// 그리고리 이펙트(머리위에)
			EFFECTSPRITETYPE_NEMA,						// 네마
			EFFECTSPRITETYPE_LEGIOS,					// 레지오스
			EFFECTSPRITETYPE_MIHOLE,					// 미호레
			EFFECTSPRITETYPE_AROSA,						// 아로사
			EFFECTSPRITETYPE_ARMEGA,					// 아르메가
			EFFECTSPRITETYPE_INI,						// 아이니
			EFFECTSPRITETYPE_JAVE,						// 쟈브
			EFFECTSPRITETYPE_CHASPA,					// 차스파
			EFFECTSPRITETYPE_CONCILIA,					// 콘칠리아
			EFFECTSPRITETYPE_KIRO,						// 키로
			EFFECTSPRITETYPE_HILLEL,					// 힐릴
			EFFECTSPRITETYPE_WARP_BLOOD_BIBLE_HOLY,		// 성지성단 워프
			EFFECTSPRITETYPE_WARP_BLOOD_BIBLE_CASTLE,	// 수호성단 워프
			EFFECTSPRITETYPE_DROP_BLOOD_BIBLE,
			EFFECTSPRITETYPE_WARP_BLOOD_BIBLE_HEAD ,  // 머리위에서 워프
			EFFECTSPRITETYPE_WARP_BLOOD_BIBLE_TILE , // 30
			EFFECTSPRITETYPE_GREGORI_TILE,					// 그리고리 이펙트(타일에 붙는것)
			EFFECTSPRITETYPE_NEMA_TILE,						// 네마
			EFFECTSPRITETYPE_LEGIOS_TILE,					// 레지오스
			EFFECTSPRITETYPE_MIHOLE_TILE,					// 미호레
			EFFECTSPRITETYPE_AROSA_TILE,						// 아로사
			EFFECTSPRITETYPE_ARMEGA_TILE,					// 아르메가
			EFFECTSPRITETYPE_INI_TILE,						// 아이니
			EFFECTSPRITETYPE_JAVE_TILE,						// 쟈브
			EFFECTSPRITETYPE_CHASPA_TILE,					// 차스파
			EFFECTSPRITETYPE_CONCILIA_TILE,					// 콘칠리아
			EFFECTSPRITETYPE_KIRO_TILE,						// 키로
			EFFECTSPRITETYPE_HILLEL_TILE,					// 힐릴
			EFFECTSPRITETYPE_STATUE_BACK_LIGHT,
			EFFECTSPRITETYPE_PK_ZONE_RESURRECTION,					
			EFFECTSPRITETYPE_MAGIC_ELUSION_END ,
			EFFECTSPRITETYPE_MAGIC_ELUSION_ING ,
			EFFECTSPRITETYPE_MAGIC_ELUSION_END ,
			EFFECTSPRITETYPE_WILL_OF_LIFE ,
			EFFECTSPRITETYPE_ILLUSION_OF_AVENGE_TILE ,
			EFFECTSPRITETYPE_ILLUSION_OF_AVENGE , //50
			EFFECTSPRITETYPE_AMATA,								// 아마타
			EFFECTSPRITETYPE_RIPATY,							// 리파티
			EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER_FRONT ,
			EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER_BACK ,
			EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER ,
			EFFECTSPRITETYPE_SWORD_RAY_1 ,
			EFFECTSPRITETYPE_SWORD_RAY_2 ,
			EFFECTSPRITETYPE_SWORD_RAY_3 ,
			EFFECTSPRITETYPE_REQUITAL_GROUND ,
			EFFECTSPRITETYPE_REQUITAL ,
			EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER ,
			EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER_BACK ,
			EFFECTSPRITETYPE_DRAGON_FIRE_CRACKER_FRONT , //65											
			EFFECTSPRITETYPE_LIGHTNESS_1 ,
			EFFECTSPRITETYPE_LIGHTNESS_2 ,
			EFFECTSPRITETYPE_LIGHTNESS_3 ,
			
			EFFECTSPRITETYPE_WATER_START_1 ,
			EFFECTSPRITETYPE_WATER_START_2 ,
			EFFECTSPRITETYPE_WATER_START_3 ,
			EFFECTSPRITETYPE_BACK_STAB_1 ,
			EFFECTSPRITETYPE_BACK_STAB_2 ,
			EFFECTSPRITETYPE_BLAZE_BOLT ,
			EFFECTSPRITETYPE_BLUNTING ,
			EFFECTSPRITETYPE_CROSS_GUARD ,
			EFFECTSPRITETYPE_EVADE ,
			EFFECTSPRITETYPE_GAMMA_CHOP_1 ,
			EFFECTSPRITETYPE_GAMMA_CHOP_2 ,
			EFFECTSPRITETYPE_GAMMA_CHOP_3 ,
			EFFECTSPRITETYPE_HAND_NIZE ,
			EFFECTSPRITETYPE_HANDS_OF_FIRE_1 ,
			EFFECTSPRITETYPE_HANDS_OF_FIRE_2 ,
			EFFECTSPRITETYPE_ICE_FIELD_1 ,
			EFFECTSPRITETYPE_ICE_FIELD_2 ,
			EFFECTSPRITETYPE_ICE_FIELD_3 ,
			EFFECTSPRITETYPE_KARAS_ARROW ,
			EFFECTSPRITETYPE_NYMPH_RECOVERY ,
			EFFECTSPRITETYPE_PROMINENCE_ING ,
			EFFECTSPRITETYPE_PROMINENCE_END ,
			EFFECTSPRITETYPE_PROMINENCE_START ,
			EFFECTSPRITETYPE_REFUSAL_1 ,
			EFFECTSPRITETYPE_REFUSAL_2 ,
			EFFECTSPRITETYPE_RING_OF_FLARE ,
			EFFECTSPRITETYPE_WATER_BARRIER_1 ,
			EFFECTSPRITETYPE_WATER_BARRIER_2 ,
			EFFECTSPRITETYPE_GROUND_START_1 ,
			EFFECTSPRITETYPE_GROUND_START_2 ,
			EFFECTSPRITETYPE_FIRE_START_1 ,
			EFFECTSPRITETYPE_FIRE_START_2 ,
			EFFECTSPRITETYPE_OUSTERS_LEVELUP_GROUND ,
			EFFECTSPRITETYPE_OUSTERS_LEVELUP_BACK ,
			EFFECTSPRITETYPE_REFUSAL2_1,	
			EFFECTSPRITETYPE_REFUSAL2_2,					
			EFFECTSPRITETYPE_REFUSAL3_1,	
			EFFECTSPRITETYPE_REFUSAL3_2,
			EFFECTSPRITETYPE_HAND_NIZE_2,
			EFFECTSPRITETYPE_HAND_NIZE_3,
			EFFECTSPRITETYPE_NYMPH_RECOVERY_2,
			EFFECTSPRITETYPE_NYMPH_RECOVERY_3,
			EFFECTSPRITETYPE_RING_OF_FLARE2,
			EFFECTSPRITETYPE_RING_OF_FLARE,
			
			EFFECTSPRITETYPE_BACK_STAB2,
			EFFECTSPRITETYPE_BACK_STAB2_2,
			EFFECTSPRITETYPE_GAMMA_CHOP2_1,
			EFFECTSPRITETYPE_GAMMA_CHOP2_2,
			EFFECTSPRITETYPE_GAMMA_CHOP2_3,
			EFFECTSPRITETYPE_GAMMA_CHOP3_1,
			EFFECTSPRITETYPE_GAMMA_CHOP3_2,
			EFFECTSPRITETYPE_GAMMA_CHOP3_3,
			EFFECTSPRITETYPE_CROSS_GUARD_2,
			EFFECTSPRITETYPE_CROSS_GUARD_3,
			
			EFFECTSPRITETYPE_PROMINENCE2_ING,					// 불지르기 진행
			EFFECTSPRITETYPE_PROMINENCE2_END,					// 불지르기 끝
			EFFECTSPRITETYPE_PROMINENCE2_START,					// 불지르기 시작
			
			EFFECTSPRITETYPE_PROMINENCE3_ING,					// 불지르기 진행
			EFFECTSPRITETYPE_PROMINENCE3_END,					// 불지르기 끝
			EFFECTSPRITETYPE_PROMINENCE3_START,					// 불지르기 시작
			EFFECTSPRITETYPE_MAP_ALTAR_OF_THORN,
			EFFECTSPRITETYPE_REFUSAL2_1,	
			EFFECTSPRITETYPE_REFUSAL2_2,			
			EFFECTSPRITETYPE_REFUSAL3_1,	
			EFFECTSPRITETYPE_REFUSAL3_2,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_AR_MALE,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_SMG_MALE,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_AR_FEMALE,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_SMG_FEMALE,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_SR_MALE,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_SG_MALE,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_SR_FEMALE,
			EFFECTSPRITETYPE_JABBING_VEIN_GUN_SG_FEMALE,

			EFFECTSPRITETYPE_HOLY_POTION_START,
			EFFECTSPRITETYPE_HOLY_POTION_ING,
			EFFECTSPRITETYPE_HOLY_POTION_END,	
			
			EFFECTSPRITETYPE_BOMBING_STAR_DROP, //빛덩어리-내려오기
			EFFECTSPRITETYPE_BOMBING_STAR_BLOW, //빛덩어리-터짐
			
			EFFECTSPRITETYPE_QUEST_MAGIC_ZONE, // 퀘스트맵 바닥 마법진 
			
#if __CONTENTS(__SECOND_RARE_SKILL)
			EFFECTSPRITETYPE_GENESIS_DROP,
			EFFECTSPRITETYPE_GENESIS_BLOW,
#endif //__SECOND_RARE_SKILL
	};
	
	int numZeroLightScreen = 16*2+31*2;
	int estDarknessScreen[] = {
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_STAND_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_STAND_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_MAGIC_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_MAGIC_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_DAMAGED_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_DAMAGED_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_DRAINED_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_DRAINED_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_DRAIN_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_DRAIN_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_ATTACK_SLOW_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_ATTACK_SLOW_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_ATTACK_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_ATTACK_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_ATTACK_FAST_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_MALE_ATTACK_FAST_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_STAND_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_STAND_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_MAGIC_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_MAGIC_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_DAMAGED_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_DAMAGED_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_DRAINED_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_DRAINED_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_DRAIN_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_DRAIN_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_ATTACK_SLOW_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_ATTACK_SLOW_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_ATTACK_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_ATTACK_FRONT,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_ATTACK_FAST_BACK,
		EFFECTSPRITETYPE_VAMPIRE_GRANDMASTER_FEMALE_ATTACK_FAST_FRONT,
		
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_STAND,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_MOVE,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_ATTACK,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_MAGIC,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_DAMAGED,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_THROW_WEAPON,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_THROW_POTION,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SWORD_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SWORD,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SWORD_FAST,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_BLADE_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_BLADE,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_BLADE_FAST,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_AR_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_AR,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_AR_FAST,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SR_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SR,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SR_FAST,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SMG_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SMG,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SMG_FAST,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SG_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SG,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SG_FAST,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SWORD_2_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SWORD_2,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_SWORD_2_FAST,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_BLADE_2_SLOW,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_BLADE_2,
		EFFECTSPRITETYPE_SLAYER_MALE_GRANDMASTER_BLADE_2_FAST,
		
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_STAND,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_MOVE,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_ATTACK,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_MAGIC,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_DAMAGED,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_THROW_WEAPON,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_THROW_POTION,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SWORD_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SWORD,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SWORD_FAST,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_BLADE_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_BLADE,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_BLADE_FAST,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_AR_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_AR,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_AR_FAST,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SR_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SR,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SR_FAST,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SMG_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SMG,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SMG_FAST,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SG_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SG,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SG_FAST,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SWORD_2_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SWORD_2,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_SWORD_2_FAST,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_BLADE_2_SLOW,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_BLADE_2,
		EFFECTSPRITETYPE_SLAYER_FEMALE_GRANDMASTER_BLADE_2_FAST,
	};
	
	for (est=0; est<sizeof(estLight)/sizeof(int); est++)
	{
		DIRECTION_EFFECTFRAME_ARRAY& DEA = ScreenEFPK[estLight[est]-MAX_EFFECTSPRITETYPE_ALPHAEFFECT];
		
		for (int d=0; d<8; d++)
		{
			EFFECTFRAME_ARRAY& EFA = DEA[d];
			
			for (int f=0; f<EFA.GetSize(); f++)
			{
				CEffectFrame& frame = EFA[f];
				
				// 빛 크기에 +5를 해준다.
				frame.Set( frame.GetSpriteID(), frame.GetCX(), frame.GetCY(), 
					frame.GetLight()+5, frame.IsBackground() );
			}
		}
	}
	for (est=0; est<numZeroLightScreen; est++)
	{
		DIRECTION_EFFECTFRAME_ARRAY& DEA = ScreenEFPK[estDarknessScreen[est]-MAX_EFFECTSPRITETYPE_ALPHAEFFECT];
		
		for (int d=0; d<8; d++)
		{
			EFFECTFRAME_ARRAY& EFA = DEA[d];
			
			for (int f=0; f<EFA.GetSize(); f++)
			{
				CEffectFrame& frame = EFA[f];
				
				frame.Set( frame.GetSpriteID(), frame.GetCX(), frame.GetCY(), 0, frame.IsBackground() );							
			}
		}
	}
	//---------------------------------------------------------------------
	// 임의의 값
	//---------------------------------------------------------------------		
	int estSpecial[] = {
		EFFECTSPRITETYPE_BLESS_ING_NEW
	};
	
	for (est=0; est<sizeof(estSpecial)/sizeof(int); est++)
	{
		switch (estSpecial[est])
		{
			//				case EFFECTSPRITETYPE_BLESS_ING :
		case EFFECTSPRITETYPE_BLESS_ING_NEW :
			lightEffect = 3;
			break;
		}
		
		int est2 = estSpecial[est]-MAX_EFFECTSPRITETYPE_ALPHAEFFECT;
		
		DIRECTION_EFFECTFRAME_ARRAY& DEA = ScreenEFPK[est2];
		
		for (int d=0; d<8; d++)
		{
			EFFECTFRAME_ARRAY& EFA = DEA[d];
			
			for (int f=0; f<EFA.GetSize(); f++)
			{
				CEffectFrame& frame = EFA[f];
				
				frame.Set( frame.GetSpriteID(), frame.GetCX(), frame.GetCY(), lightEffect, frame.IsBackground() );							
			}
		}
	}
}


void InitAlphaEffectLight(CEffectFramePack& EFPK)
{
	//---------------------------------------------------------------------
	// darkness 3개..
	//---------------------------------------------------------------------		

	
//	const int numZeroLight = 23 + 120 + 25 + 64 + 48 + 5;

	int estLightness[] = {
		EFFECTSPRITETYPE_EMISSION_WATER_2,
		EFFECTSPRITETYPE_EMISSION_WATER_3,
		EFFECTSPRITETYPE_MAP_PILAR_OF_FIRE_MIDIUM,
		EFFECTSPRITETYPE_MAP_LIGHT_OF_SOUL,
		EFFECTSPRITETYPE_MAP_PILAR_OF_FIRE_SMALL,
		EFFECTSPRITETYPE_MAP_PILAR_OF_FIRE_LARGE,
		EFFECTSPRITETYPE_SHARP_ROUND_1_2,
		EFFECTSPRITETYPE_SHARP_ROUND_2_2,
		
		EFFECTSPRITETYPE_SHARP_ROUND_1,
		EFFECTSPRITETYPE_SHARP_ROUND_2,
		EFFECTSPRITETYPE_SAND_OF_SOUL_STONE,
		EFFECTSPRITETYPE_SAND_OF_SOUL_STONE_GROUND,
		EFFECTSPRITETYPE_FIRE_BURST_SMALL,
		EFFECTSPRITETYPE_FIRE_BURST_MEDIUM,
		EFFECTSPRITETYPE_SHARP_ROUND_1_3,
		EFFECTSPRITETYPE_SHARP_ROUND_2_3,
		EFFECTSPRITETYPE_MULTI_AMPUTATE_1,			// MULTI AMPUTATE 공격
		EFFECTSPRITETYPE_MULTI_AMPUTATE_2,			// MULTI AMPUTATE 부서짐
		EFFECTSPRITETYPE_GREAT_HEAL,
		EFFECTSPRITETYPE_JABBING_VEIN_FRONT_1,
		EFFECTSPRITETYPE_JABBING_VEIN_FRONT_2,
		EFFECTSPRITETYPE_JABBING_VEIN_FRONT_3,
		EFFECTSPRITETYPE_JABBING_VEIN_FRONT_4,
		
		EFFECTSPRITETYPE_JABBING_VEIN_FRONT_GOLEMER,
		EFFECTSPRITETYPE_JABBING_VEIN_FRONT_ALCAN,
		EFFECTSPRITETYPE_JABBING_VEIN_FRONT_BAT,
		
		EFFECTSPRITETYPE_JABBING_VEIN_REAR_1,
		EFFECTSPRITETYPE_JABBING_VEIN_REAR_2,
		EFFECTSPRITETYPE_JABBING_VEIN_REAR_3,
		EFFECTSPRITETYPE_JABBING_VEIN_REAR_4,
		
		EFFECTSPRITETYPE_JABBING_VEIN_REAR_GOLEMER,
		EFFECTSPRITETYPE_JABBING_VEIN_REAR_ALCAN,
		EFFECTSPRITETYPE_JABBING_VEIN_REAR_BAT,
		
		EFFECTSPRITETYPE_LIGHT_SWORD_MALE,
		EFFECTSPRITETYPE_LIGHT_SWORD_FEMALE,
		EFFECTSPRITETYPE_BLITZ_SLIDING_DROP,
		EFFECTSPRITETYPE_BLITZ_SLIDING_BOMB,
		EFFECTSPRITETYPE_BLITZ_SLIDING_SPARK,
		
		EFFECTSPRITETYPE_BLAZE_WALK_FEMALE,
		EFFECTSPRITETYPE_BLAZE_WALK_MALE,
		
		EFFECTSPRITETYPE_ETERNITY_GROUND,
		EFFECTSPRITETYPE_HEAD_SHOT,
		EFFECTSPRITETYPE_ETERNITY,
		EFFECTSPRITETYPE_PIERCING_BACK,
		EFFECTSPRITETYPE_PIERCING_FRONT,
		EFFECTSPRITETYPE_MOLE_SHOT_1,
		EFFECTSPRITETYPE_MOLE_SHOT_2,
		EFFECTSPRITETYPE_MOLE_SHOT_3,
		EFFECTSPRITETYPE_MOLE_SHOT_4,
		EFFECTSPRITETYPE_MOLE_SHOT_5,	
		
		EFFECTSPRITETYPE_TRIDENT_BOMB_1,
		EFFECTSPRITETYPE_TRIDENT_BOMB_2,
		EFFECTSPRITETYPE_TRIDENT_BOMB_3,
		EFFECTSPRITETYPE_TRIDENT_BOMB_4,
		EFFECTSPRITETYPE_TRIDENT_BOMB_5,
		
		EFFECTSPRITETYPE_TRIDENT_SMALL_BOMB_1,
		EFFECTSPRITETYPE_TRIDENT_SMALL_BOMB_2,
		EFFECTSPRITETYPE_TRIDENT_SMALL_BOMB_3,
		EFFECTSPRITETYPE_TRIDENT_SMALL_BOMB_4,
		EFFECTSPRITETYPE_TRIDENT_SMALL_BOMB_5,
		
		EFFECTSPRITETYPE_QUICK_FIRE_BOMB_1,
		EFFECTSPRITETYPE_QUICK_FIRE_BOMB_2,
		EFFECTSPRITETYPE_QUICK_FIRE_BOMB_3,
		EFFECTSPRITETYPE_QUICK_FIRE_BOMB_4,
		EFFECTSPRITETYPE_QUICK_FIRE_BOMB_5,

		EFFECTSPRITETYPE_PROTECTION_FROM_BLOOD_BACK,
		EFFECTSPRITETYPE_PROTECTION_FROM_BLOOD_FRONT,
		EFFECTSPRITETYPE_REGEN_TOWER_GROUND,
		EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_START,
		EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_ING,
		EFFECTSPRITETYPE_REGEN_TOWER_THROW_LIGHT_END,
		EFFECTSPRITETYPE_BEAD_BLUE_1,
		EFFECTSPRITETYPE_BEAD_BLUE_2,
		EFFECTSPRITETYPE_BEAD_BLUE_3,
		EFFECTSPRITETYPE_BEAD_BLUE_4,

		EFFECTSPRITETYPE_BEAD_GREEN_1,
		EFFECTSPRITETYPE_BEAD_GREEN_2,
		EFFECTSPRITETYPE_BEAD_GREEN_3,
		EFFECTSPRITETYPE_BEAD_GREEN_4,

		EFFECTSPRITETYPE_BEAD_RED_1,
		EFFECTSPRITETYPE_BEAD_RED_2,
		EFFECTSPRITETYPE_BEAD_RED_3,
		EFFECTSPRITETYPE_BEAD_RED_4,

		EFFECTSPRITETYPE_HAS_SWEEPER_ORANGE,
		EFFECTSPRITETYPE_HAS_SWEEPER_GREEN,
		EFFECTSPRITETYPE_HAS_SWEEPER_WHITE,

		EFFECTSPRITETYPE_REGEN_TOWER_DROP_LIGHT,
		EFFECTSPRITETYPE_REGEN_TOWER_RIGHT_BEAD,

		
		EFFECTSPRITETYPE_BURNING_SOL_BLOW_1,	// 버닝 솔 터지기 1 단계
		EFFECTSPRITETYPE_BURNING_SOL_BLOW_2,	// 버닝 솔 터지기 2 단계
		EFFECTSPRITETYPE_BURNING_SOL_BLOW_3,	// 버닝 솔 터지기 3 단계
		EFFECTSPRITETYPE_BURNING_SOL_BLOW_4,	// 버닝 솔 터지기 4 단계
		EFFECTSPRITETYPE_SWORD_OF_THOR_LOOP_SWORD,
		EFFECTSPRITETYPE_WHITSUNTIDE,
		EFFECTSPRITETYPE_SWEEP_VICE_END_1,		// 스윕 바이스 사라지기 1
		EFFECTSPRITETYPE_SWEEP_VICE_START_1,	// 스윕 바이스 생성 1
		EFFECTSPRITETYPE_SWEEP_VICE_END_2,		// 스윕 바이스 사라지기 2
		EFFECTSPRITETYPE_SWEEP_VICE_START_2,	// 스윕 바이스 생성 2
		EFFECTSPRITETYPE_SWEEP_VICE_END_3,		// 스윕 바이스 사라지기 3
		EFFECTSPRITETYPE_SWEEP_VICE_START_3,	// 스윕 바이스 생성 3

		EFFECTSPRITETYPE_INFINITY_THUNDERBOLT_CENTER,//검140-번개A타입
		EFFECTSPRITETYPE_INFINITY_THUNDERBOLT_LEFT,//검140-번개B타입
		EFFECTSPRITETYPE_INFINITY_THUNDERBOLT_RIGHT,//검140-번개C타입
		EFFECTSPRITETYPE_INTIMATE_GRAIL_LIGHT,//황금잔-중앙빛
		EFFECTSPRITETYPE_NEW_PLASMA_ROCKET_LAUNCHER_BLOW,			//플라즈마-폭발
		EFFECTSPRITETYPE_ICE_HORIZON_LOOP,				//물140-소환얼음-반복
		EFFECTSPRITETYPE_SUMMON_MIGA_BLOW,				//불계열140-몸에붙는불-폭파

		EFFECTSPRITETYPE_DRAGON_EYE,						// 드레곤 아이
		EFFECTSPRITETYPE_NEW_PLASMA_ROCKET_LAUNCHER_BLOW,	// 총슬 140 스킬 터지기
		EFFECTSPRITETYPE_ICE_HORIZON_LOOP,					// 물아우 140 스킬
		EFFECTSPRITETYPE_SUMMON_MIGA_BLOW,					// 불아우 서먼 미가 터지기
		EFFECTSPRITETYPE_FIERCE_FLAME_BLOW,					// 불아우 150 스킬 터지기
		EFFECTSPRITETYPE_ROTTEN_APPLE,						// 인첸 150 터지기
		EFFECTSPRITETYPE_BIKE_CRASH,						// 검슬 150 이펙트
		EFFECTSPRITETYPE_HALO,								// 전투 아우 150 이펙트
		EFFECTSPRITETYPE_CANDLE_START,						// 촛불 이벤트
		
		EFFECTSPRITETYPE_UNTERFELDWEBEL_BALKANS_FIRE ,
		EFFECTSPRITETYPE_FELDWEBEL_CLAYDOLL_FIRE  ,
#if __CONTENTS(__SECOND_RARE_SKILL)
		EFFECTSPRITETYPE_HEAVENLY_SPARK_RIGHT,
		EFFECTSPRITETYPE_HEAVENLY_SPARK_LEFT,
		EFFECTSPRITETYPE_HEAVENLY_SPARK_CENTER,
		EFFECTSPRITETYPE_XRL_EXPLOSION,
#endif //__SECOND_RARE_SKILL
	};
	
	int estDarkness[] = {
		EFFECTSPRITETYPE_DARKNESS_1_1,
		EFFECTSPRITETYPE_DARKNESS_1_2,
		EFFECTSPRITETYPE_DARKNESS_1,
		EFFECTSPRITETYPE_DARKNESS_1_4,
		EFFECTSPRITETYPE_DARKNESS_1_5,
		EFFECTSPRITETYPE_DARKNESS_2_1,
		EFFECTSPRITETYPE_DARKNESS_2_2,
		EFFECTSPRITETYPE_DARKNESS_2,
		EFFECTSPRITETYPE_DARKNESS_2_4,
		EFFECTSPRITETYPE_DARKNESS_2_5,
		EFFECTSPRITETYPE_DARKNESS_3_1,
		EFFECTSPRITETYPE_DARKNESS_3_2,
		EFFECTSPRITETYPE_DARKNESS_3,
		EFFECTSPRITETYPE_DARKNESS_3_4,
		EFFECTSPRITETYPE_DARKNESS_3_5,
		EFFECTSPRITETYPE_YELLOW_POISON_1,
		EFFECTSPRITETYPE_YELLOW_POISON_2,
		EFFECTSPRITETYPE_YELLOW_POISON_3,
		
		EFFECTSPRITETYPE_CHARM_1,
		EFFECTSPRITETYPE_CHARM_2,
		EFFECTSPRITETYPE_POLYMORPH_BACK,
		EFFECTSPRITETYPE_POLYMORPH_FRONT,
		EFFECTSPRITETYPE_MEPHISTO,
		
		// berserker(120개)
		EFFECTSPRITETYPE_BERSERKER_1_STAND_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_STAND_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_STAND_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_STAND_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_STAND_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_STAND_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_STAND_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_STAND_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_STAND_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_STAND_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_STAND_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_STAND_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_MOVE_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_MOVE_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_MOVE_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_MOVE_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_MOVE_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_MOVE_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_MOVE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_MOVE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_MOVE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_MOVE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_MOVE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_MOVE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_MAGIC_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_MAGIC_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_MAGIC_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_MAGIC_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_MAGIC_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_MAGIC_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_MAGIC_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_MAGIC_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_MAGIC_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_MAGIC_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_MAGIC_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_MAGIC_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_DAMAGE_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_DAMAGE_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_DAMAGE_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_DAMAGE_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_DAMAGE_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_DAMAGE_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE2_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE2_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE2_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE2_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE2_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE2_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE2_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE2_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE2_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE2_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE2_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE2_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE2_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE2_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE2_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE2_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE2_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE2_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE2_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE2_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE2_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE2_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE2_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE2_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE2_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE2_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE2_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE2_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE2_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE2_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE2_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE2_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE2_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE2_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE2_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE2_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE_FAST_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE_FAST_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE_SLOW_MALE,
		EFFECTSPRITETYPE_BERSERKER_1_BLADE_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_2_BLADE_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_3_BLADE_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_4_BLADE_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_5_BLADE_SLOW_FEMALE,
		EFFECTSPRITETYPE_BERSERKER_6_BLADE_SLOW_FEMALE,
		
		// HP Boost(25개)
		EFFECTSPRITETYPE_HPBOOST_STAND_MALE,
		EFFECTSPRITETYPE_HPBOOST_MOVE_MALE,
		EFFECTSPRITETYPE_HPBOOST_ATTACK_MALE,
		EFFECTSPRITETYPE_HPBOOST_MAGIC_MALE,
		EFFECTSPRITETYPE_HPBOOST_DAMAGE_MALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD_FAST_MALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD2_FAST_MALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD_MALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD_SLOW_MALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD2_SLOW_MALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD2_MALE,
		EFFECTSPRITETYPE_HPBOOST_THROW_MALE,
		EFFECTSPRITETYPE_HPBOOST_CASTING,
		EFFECTSPRITETYPE_HPBOOST_STAND_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_MOVE_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_ATTACK_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_MAGIC_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD_FAST_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD2_SLOW_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD_SLOW_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD2_FAST_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_SWORD2_FEMALE,
		EFFECTSPRITETYPE_HPBOOST_THROW_FEMALE,
		
		// Regen (64개)
		EFFECTSPRITETYPE_REGENERATION_1_STAND_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_STAND_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_STAND_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_STAND_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_1_MOVE_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_MOVE_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_MOVE_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_MOVE_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_ATTACK_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_ATTACK_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_ATTACK_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_ATTACK_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_MAGIC_MALE	,
		EFFECTSPRITETYPE_REGENERATION_2_MAGIC_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_MAGIC_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_MAGIC_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_DAMAGE_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_DAMAGE_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_DAMAGE_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_AR_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_AR_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_AR_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_AR_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_SR_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_SR_MALE,
		EFFECTSPRITETYPE_REGENERATION_1_SR_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_SR_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_1_SWORD_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_SWORD_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_SWORD_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_SWORD_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_BLADE_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_BLADE_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_BLADE_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_BLADE_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_THROW_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_THROW_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_THROW_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_THROW_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_MOTOR_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_MOTOR_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_MOTOR_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_MOTOR_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_SG_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_SG_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_SG_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_SG_FEMALE ,
		EFFECTSPRITETYPE_REGENERATION_1_SMG_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_SMG_MALE ,
		EFFECTSPRITETYPE_REGENERATION_1_SMG_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_SMG_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_1_SWORD2_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_SWORD2_MALE,
		EFFECTSPRITETYPE_REGENERATION_1_SWORD2_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_SWORD2_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_1_BLADE2_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_BLADE2_MALE,
		EFFECTSPRITETYPE_REGENERATION_1_BLADE2_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_BLADE2_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_1_THROW2_MALE,
		EFFECTSPRITETYPE_REGENERATION_2_THROW2_MALE,
		EFFECTSPRITETYPE_REGENERATION_1_THROW2_FEMALE,
		EFFECTSPRITETYPE_REGENERATION_2_THROW2_FEMALE,
		
		// extreme (48개)
		EFFECTSPRITETYPE_EXTREME_L_1_STAND_MALE,	// 뱀파 어깨에 붙는 검은 기운.
		EFFECTSPRITETYPE_EXTREME_L_2_STAND_MALE,	// 아마도(-_-;) 왼쪽에 2개, 오른쪽에 2개..
		EFFECTSPRITETYPE_EXTREME_R_1_STAND_MALE,
		EFFECTSPRITETYPE_EXTREME_R_2_STAND_MALE,
		EFFECTSPRITETYPE_EXTREME_L_1_MOVE_MALE,
		EFFECTSPRITETYPE_EXTREME_L_2_MOVE_MALE,
		EFFECTSPRITETYPE_EXTREME_R_1_MOVE_MALE,
		EFFECTSPRITETYPE_EXTREME_R_2_MOVE_MALE,
		EFFECTSPRITETYPE_EXTREME_L_1_ATTACK_MALE,
		EFFECTSPRITETYPE_EXTREME_L_2_ATTACK_MALE,
		EFFECTSPRITETYPE_EXTREME_R_1_ATTACK_MALE,
		EFFECTSPRITETYPE_EXTREME_R_2_ATTACK_MALE,
		EFFECTSPRITETYPE_EXTREME_L_1_ATTACK_SLOW_MALE,
		EFFECTSPRITETYPE_EXTREME_L_2_ATTACK_SLOW_MALE,
		EFFECTSPRITETYPE_EXTREME_R_1_ATTACK_SLOW_MALE,
		EFFECTSPRITETYPE_EXTREME_R_2_ATTACK_SLOW_MALE,
		EFFECTSPRITETYPE_EXTREME_L_1_ATTACK_FAST_MALE,
		EFFECTSPRITETYPE_EXTREME_L_2_ATTACK_FAST_MALE,
		EFFECTSPRITETYPE_EXTREME_R_1_ATTACK_FAST_MALE,
		EFFECTSPRITETYPE_EXTREME_R_2_ATTACK_FAST_MALE,
		EFFECTSPRITETYPE_EXTREME_L_1_DAMAGE_MALE,
		EFFECTSPRITETYPE_EXTREME_L_2_DAMAGE_MALE,
		EFFECTSPRITETYPE_EXTREME_R_1_DAMAGE_MALE,
		EFFECTSPRITETYPE_EXTREME_R_2_DAMAGE_MALE,
		EFFECTSPRITETYPE_EXTREME_L_1_STAND_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_2_STAND_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_1_STAND_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_2_STAND_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_1_MOVE_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_2_MOVE_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_1_MOVE_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_2_MOVE_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_1_ATTACK_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_2_ATTACK_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_1_ATTACK_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_2_ATTACK_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_1_ATTACK_SLOW_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_2_ATTACK_SLOW_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_1_ATTACK_SLOW_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_2_ATTACK_SLOW_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_1_ATTACK_FAST_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_2_ATTACK_FAST_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_1_ATTACK_FAST_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_2_ATTACK_FAST_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_1_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_EXTREME_L_2_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_1_DAMAGE_FEMALE,
		EFFECTSPRITETYPE_EXTREME_R_2_DAMAGE_FEMALE,
		
		EFFECTSPRITETYPE_MAP_DROP_BLOOD,
		EFFECTSPRITETYPE_MAP_BUBBLE_GREEN1,
		EFFECTSPRITETYPE_MAP_BUBBLE_GREEN2,
		EFFECTSPRITETYPE_MAP_BUBBLE_RED1,
		EFFECTSPRITETYPE_MAP_BUBBLE_RED2,
		
		EFFECTSPRITETYPE_DIVINE_GUIDANCE_START,
		EFFECTSPRITETYPE_DIVINE_GUIDANCE_ING,
		EFFECTSPRITETYPE_DIVINE_GUIDANCE_END,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_STOP_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_STOP_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_STOP_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_STOP_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_STOP_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_STOP_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_STOP_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_STOP_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_STOP_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_STOP_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_MOVE_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_MOVE_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_MOVE_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_MOVE_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MOTOR_MOVE_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_STOP_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_STOP_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_STOP_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_STOP_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_STOP_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_STOP_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_STOP_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_STOP_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_STOP_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_STOP_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_MOVE_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_MOVE_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_MOVE_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_MOVE_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MOTOR_MOVE_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_WALK_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_WALK_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_WALK_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_WALK_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_WALK_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_WALK_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_WALK_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_WALK_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_WALK_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_WALK_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MAGIC_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MAGIC_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MAGIC_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MAGIC_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_MAGIC_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MAGIC_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MAGIC_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MAGIC_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MAGIC_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_MAGIC_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_DAMAGED_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_DAMAGED_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_DAMAGED_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_DAMAGED_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_DAMAGED_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_DAMAGED_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_DAMAGED_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_DAMAGED_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_DAMAGED_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_DAMAGED_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_FAST_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_FAST_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_FAST_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_FAST_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_FAST_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_NORMAL_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_NORMAL_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_NORMAL_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_NORMAL_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_NORMAL_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_SLOW_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_SLOW_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_SLOW_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_SLOW_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_ATTACK_SLOW_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_FAST_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_FAST_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_FAST_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_FAST_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_FAST_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_NORMAL_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_NORMAL_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_NORMAL_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_NORMAL_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_NORMAL_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_SLOW_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_SLOW_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_SLOW_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_SLOW_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_ATTACK_SLOW_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_FAST_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_FAST_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_FAST_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_FAST_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_FAST_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_NORMAL_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_NORMAL_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_NORMAL_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_NORMAL_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_NORMAL_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_SLOW_1,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_SLOW_2,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_SLOW_3,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_SLOW_4,
		EFFECTSPRITETYPE_CHARGING_POWER_FEMALE_SKILL_SLOW_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_FAST_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_FAST_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_FAST_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_FAST_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_FAST_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_NORMAL_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_NORMAL_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_NORMAL_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_NORMAL_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_NORMAL_5,
		
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_SLOW_1,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_SLOW_2,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_SLOW_3,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_SLOW_4,
		EFFECTSPRITETYPE_CHARGING_POWER_MALE_SKILL_SLOW_5,

	};
		
	for (int est=0; est<sizeof(estDarkness)/sizeof(int); est++)
	{
		DIRECTION_EFFECTFRAME_ARRAY& DEA = EFPK[estDarkness[est]];
		
		for (int d=0; d<8; d++)
		{
			EFFECTFRAME_ARRAY& EFA = DEA[d];
			
			for (int f=0; f<EFA.GetSize(); f++)
			{
				CEffectFrame& frame = EFA[f];
				
				frame.Set( frame.GetSpriteID(), frame.GetCX(), frame.GetCY(), 0, frame.IsBackground() );							
			}
		}
	}

	for( est = 0; est<sizeof(estLightness)/sizeof(int);est++)
	{
		DIRECTION_EFFECTFRAME_ARRAY& DEA = EFPK[estLightness[est]];

		for(int d=0;d<8;d++)
		{
			EFFECTFRAME_ARRAY& EFA = DEA[d];

			for(int f=0;f<EFA.GetSize(); f++)
			{
				CEffectFrame& frame = EFA[f];

				frame.Set( frame.GetSpriteID(), frame.GetCX(), frame.GetCY(), frame.GetLight()+5, frame.IsBackground() );
			}
		}
	}
}
