//---------------------------------------------------------------------------
// InitHelpString.cpp
//---------------------------------------------------------------------------

#include <Windows.h>
#include "MHelpStringTable.h"
#include "MFileDef.h"
#include <fstream>
#include "packet/Properties.h"

//---------------------------------------------------------------------------
// Init HelpString
//---------------------------------------------------------------------------
BOOL
InitHelpString()
{
	if (g_pHelpStringTable==NULL)
	{
		g_pHelpStringTable = new MHelpStringTable;
	}

	g_pHelpStringTable->Init( MAX_HELP_OUTPUT );

	(*g_pHelpStringTable)[HO_ALT_TO_PICKUP_ITEM] = "ALT_TO_PICKUP_ITEM";
	(*g_pHelpStringTable)[HO_ALT_TO_TRADE] = "HO_ALT_TO_TRADE";
	(*g_pHelpStringTable)[HO_ATTACK_SLAYER_TO_DRAIN] = "ATTACK_SLAYER_TO_DRAIN";
	(*g_pHelpStringTable)[HO_BELT_TOGGLE_KEY] = "BELT_TOGGLE_KEY";
	(*g_pHelpStringTable)[HO_BETTER_TO_LEARN_FAST_RELOAD_SKILL] = "BETTER_TO_LEARN_FAST_RELOAD_SKILL";
	(*g_pHelpStringTable)[HO_BROKEN_ITEM_CANNOT_BE_RESTORE] = "BROKEN_ITEM_CANNOT_BE_RESTORE";
	(*g_pHelpStringTable)[HO_CANCEL_TO_CANCEL_TRADE] = "CANCEL_TO_CANCEL_TRADE";
	(*g_pHelpStringTable)[HO_CLICK_BAR_TO_CHANGE_ITEM_TYPE] = "CLICK_BAR_TO_CHANGE_ITEM_TYPE";
	(*g_pHelpStringTable)[HO_CLICK_ITEM_TO_BUY] = "CLICK_ITEM_TO_BUY";
	(*g_pHelpStringTable)[HO_CLICK_ITEM_TO_REPAIR] = "CLICK_ITEM_TO_REPAIR";
	(*g_pHelpStringTable)[HO_CLICK_MONSTER_TO_ATTACK] = "CLICK_MONSTER_TO_ATTACK";
	(*g_pHelpStringTable)[HO_CLICK_NPC_TO_TRADE] = "CLICK_NPC_TO_TRADE";
	(*g_pHelpStringTable)[HO_CLICK_PRESS_TO_AUTO_ACTION] = "CLICK_PRESS_TO_AUTO_ACTION";
	(*g_pHelpStringTable)[HO_CLICK_TO_PICKUP] = "CLICK_TO_PICKUP";
	(*g_pHelpStringTable)[HO_CLICK_TO_PLUS_STATUS] = "CLICK_TO_PLUS_STATUS";
	(*g_pHelpStringTable)[HO_CTRL_H_TO_BASIC_HELP] = "CTRL_H_TO_BASIC_HELP";	
	(*g_pHelpStringTable)[HO_CTRL_TILDE_TO_QUICKSLOT] = "HO_CTRL_TILDE_TO_QUICKSLOT";
	(*g_pHelpStringTable)[HO_EACH_GUN_NEED_OWN_MAGAZINE] = "EACH_GUN_NEED_OWN_MAGAZINE";
	(*g_pHelpStringTable)[HO_EFFECT_BLESS] = "EFFECT_BLESS";
	(*g_pHelpStringTable)[HO_EFFECT_BURROW] = "EFFECT_BURROW";
	(*g_pHelpStringTable)[HO_EFFECT_GREEN_POISON] = "EFFECT_GREEN_POISON";
	(*g_pHelpStringTable)[HO_EFFECT_PURPLE_WALL] = "EFFECT_PURPLE_WALL";
	(*g_pHelpStringTable)[HO_EFFECT_STRIKING] = "EFFECT_STRIKING";
	(*g_pHelpStringTable)[HO_EFFECT_YELLOW_POISON] = "EFFECT_YELLOW_POISON";
	(*g_pHelpStringTable)[HO_HEAL_POTION_CAN_HEAL] = "HEAL_POTION_CAN_HEAL";
	(*g_pHelpStringTable)[HO_HOLY_WATER_DAMAGE_DECIDED_WHEN_CREATE] = "HOLY_WATER_DAMAGE_DECIDED_WHEN_CREATE";
	(*g_pHelpStringTable)[HO_HOW_TO_ACCEPT_CHAT] = "HOW_TO_ACCEPT_CHAT";
	(*g_pHelpStringTable)[HO_HOW_TO_ACCEPT_CHAT_ALL] = "HOW_TO_ACCEPT_CHAT_ALL";
	(*g_pHelpStringTable)[HO_HOW_TO_CURE_BLOOD_DRAIN] = "HOW_TO_CURE_BLOOD_DRAIN";
	(*g_pHelpStringTable)[HO_HOW_TO_CURE_GREEN_POISON] = "HOW_TO_CURE_GREEN_POISON";
	(*g_pHelpStringTable)[HO_HOW_TO_CURE_PURPLE_WALL] = "HOW_TO_CURE_PURPLE_WALL";
	(*g_pHelpStringTable)[HO_HOW_TO_CURE_YELLOW_POISON] = "HOW_TO_CURE_YELLOW_POISON";
	(*g_pHelpStringTable)[HO_HOW_TO_GET_HEAL_POTION] = "HOW_TO_GET_HEAL_POTION";
	(*g_pHelpStringTable)[HO_HOW_TO_GET_MANA_POTION] = "HOW_TO_GET_MANA_POTION";
	(*g_pHelpStringTable)[HO_HOW_TO_REJECT_CHAT] = "HOW_TO_REJECT_CHAT";
	(*g_pHelpStringTable)[HO_HOW_TO_SHOUT] = "HOW_TO_SHOUT";
	(*g_pHelpStringTable)[HO_HOW_TO_UNBURROW] = "HOW_TO_UNBURROW";
	(*g_pHelpStringTable)[HO_HOW_TO_USE_SKILL] = "HOW_TO_USE_SKILL";
	(*g_pHelpStringTable)[HO_HOW_TO_WHISPER] = "HOW_TO_WHISPER";
	(*g_pHelpStringTable)[HO_INVENTORY_MONEY_WILL_AUTO_INCREASE_] = "INVENTORY_MONEY_WILL_AUTO_INCREASE_";
	(*g_pHelpStringTable)[HO_ITEM_CAN_BE_BROKEN] = "ITEM_CAN_BE_BROKEN";
	(*g_pHelpStringTable)[HO_KEEP_MOTORCYCLE_KEY] = "KEEP_MOTORCYCLE_KEY";
	(*g_pHelpStringTable)[HO_LEFTCLICK_TO_CORPSE_TO_LOOT] = "LEFTCLICK_TO_CORPSE_TO_LOOT";
	(*g_pHelpStringTable)[HO_LEFTCLICK_TO_MOTORCYCLE_TO_RIDE] = "LEFTCLICK_TO_MOTORCYCLE_TO_RIDE";
	(*g_pHelpStringTable)[HO_MANA_POTION_CAN_FILL_MANA] = "MANA_POTION_CAN_FILL_MANA";
	(*g_pHelpStringTable)[HO_MONEY_AND_HIGH_LIGHTED_ITEM_AND_OTHER_INVENTORY_ITEM_WILL_TRADE] = "MONEY_AND_HIGH_LIGHTED_ITEM_AND_OTHER_INVENTORY_ITEM_WILL_TRADE";
	(*g_pHelpStringTable)[HO_MOVE_ITEM_TO_BELT] = "MOVE_ITEM_TO_BELT";
	(*g_pHelpStringTable)[HO_NEED_RELOAD_TO_USE_GUN] = "NEED_RELOAD_TO_USE_GUN";
	(*g_pHelpStringTable)[HO_NORMAL_ITEM_IS_BASIC_ITEM] = "NORMAL_ITEM_IS_BASIC_ITEM";
	(*g_pHelpStringTable)[HO_NPC_OUTLINE_COLOR_IS_GREEN] = "NPC_OUTLINE_COLOR_IS_GREEN";
	(*g_pHelpStringTable)[HO_OK_TO_ACCEPT_TRADE] = "OK_TO_ACCEPT_TRADE";
	(*g_pHelpStringTable)[HO_ONLY_HIGH_LIGHTED_ITEM_WILL_TRADE] = "ONLY_HIGH_LIGHTED_ITEM_WILL_TRADE";
	(*g_pHelpStringTable)[HO_ONLY_POTION_AND_MAGAZINE_CAN_STOCK_IN_BELT] = "ONLY_POTION_AND_MAGAZINE_CAN_STOCK_IN_BELT";
	(*g_pHelpStringTable)[HO_RECLICK_ITEM_TO_REMOVE_TRADE] = "RECLICK_ITEM_TO_REMOVE_TRADE";
	(*g_pHelpStringTable)[HO_RELOAD_TIME_IS_LONG] = "RELOAD_TIME_IS_LONG";
	(*g_pHelpStringTable)[HO_REPAIR_COST_IS_UP_TO_DURABILITY] = "REPAIR_COST_IS_UP_TO_DURABILITY";
	(*g_pHelpStringTable)[HO_RIGHTCLICK_ITEM_TO_ADD_TRADE] = "RIGHTCLICK_ITEM_TO_ADD_TRADE";
	(*g_pHelpStringTable)[HO_RIGHTCLICK_ITEM_TO_SHOW] = "RIGHTCLICK_ITEM_TO_SHOW";
	(*g_pHelpStringTable)[HO_SLASH_TO_QUICK_WHISPER] = "SLASH_TO_QUICK_WHISPER";
	(*g_pHelpStringTable)[HO_SPECIAL_ITEM_IS_GOOD] = "SPECIAL_ITEM_IS_GOOD";
	(*g_pHelpStringTable)[HO_THERE_IS_MONEY] = "THERE_IS_MONEY";
	(*g_pHelpStringTable)[HO_THERE_IS_SOME_ITEMS_IN_CORPSE] = "THERE_IS_SOME_ITEMS_IN_CORPSE";
	(*g_pHelpStringTable)[HO_TIME_RESTRICT_SHOUT] = "TIME_RESTRICT_SHOUT";
	(*g_pHelpStringTable)[HO_USE_BLADE_TO_INCREASE_BLADE_SKILL] = "USE_BLADE_TO_INCREASE_BLADE_SKILL";
	(*g_pHelpStringTable)[HO_USE_CROSS_TO_INCREASE_HEAL_SKILL] = "USE_CROSS_TO_INCREASE_HEAL_SKILL";
	(*g_pHelpStringTable)[HO_USE_FUNCTION_KEY_FOR_QUICKITEM] = "USE_FUNCTION_KEY_FOR_QUICKITEM";
	(*g_pHelpStringTable)[HO_USE_FUNCTION_KEY_TO_SELECT_SKILL] = "USE_FUNCTION_KEY_TO_SELECT_SKILL";
	(*g_pHelpStringTable)[HO_USE_GUN_TO_INCREASE_GUN_SKILL] = "USE_GUN_TO_INCREASE_GUN_SKILL";
	(*g_pHelpStringTable)[HO_USE_HP_POTION_IN_BELT] = "USE_HP_POTION_IN_BELT";
	(*g_pHelpStringTable)[HO_USE_HP_POTION_IN_INVENTORY] = "USE_HP_POTION_IN_INVENTORY";
	(*g_pHelpStringTable)[HO_USE_MACE_TO_INCREASE_ENCHANT_SKILL] = "USE_MACE_TO_INCREASE_ENCHANT_SKILL";
	(*g_pHelpStringTable)[HO_USE_MAGAZINE_IN_INVENTORY_TO_RELOAD] = "USE_MAGAZINE_IN_INVENTORY_TO_RELOAD";
	(*g_pHelpStringTable)[HO_USE_MANA_POTION_IN_BELT] = "USE_MANA_POTION_IN_BELT";
	(*g_pHelpStringTable)[HO_USE_MANA_POTION_IN_INVENTORY] = "USE_MANA_POTION_IN_INVENTORY";
	(*g_pHelpStringTable)[HO_USE_SWORD_TO_INCREASE_SWORD_SKILL] = "USE_SWORD_TO_INCREASE_SWORD_SKILL";
	(*g_pHelpStringTable)[HO_VAMPIRE_IS_DANGEROUS] = "VAMPIRE_IS_DANGEROUS";
	(*g_pHelpStringTable)[HO_VAMPIRE_IS_OTHER_PLAYER] = "VAMPIRE_IS_OTHER_PLAYER";
	(*g_pHelpStringTable)[HO_WHERE_CAN_LEARN_BLADE_SKILL] = "WHERE_CAN_LEARN_BLADE_SKILL";
	(*g_pHelpStringTable)[HO_WHERE_CAN_LEARN_ENCHANT_SKILL] = "WHERE_CAN_LEARN_ENCHANT_SKILL";
	(*g_pHelpStringTable)[HO_WHERE_CAN_LEARN_GUN_SKILL] = "WHERE_CAN_LEARN_GUN_SKILL";
	(*g_pHelpStringTable)[HO_WHERE_CAN_LEARN_HEAL_SKILL] = "WHERE_CAN_LEARN_HEAL_SKILL";
	(*g_pHelpStringTable)[HO_WHERE_CAN_LEARN_SWORD_SKILL] = "WHERE_CAN_LEARN_SWORD_SKILL";
	(*g_pHelpStringTable)[HO_WHERE_CAN_LEARN_VAMPIRE_SKILL] = "WHERE_CAN_LEARN_VAMPIRE_SKILL";
	(*g_pHelpStringTable)[HO_WHERE_TO_REPAIR] = "WHERE_TO_REPAIR";
	(*g_pHelpStringTable)[HO_YOU_CANNOT_ANY_ACTION_WHEN_RIDE_MOTORCYCLE] = "YOU_CANNOT_ANY_ACTION_WHEN_RIDE_MOTORCYCLE";
	(*g_pHelpStringTable)[HO_YOU_CANNOT_USE_RED_ITEM] = "YOU_CANNOT_USE_RED_ITEM";
	(*g_pHelpStringTable)[HO_YOU_CANNOT_USE_SHIELD_WITH_BLADE] = "YOU_CANNOT_USE_SHIELD_WITH_BLADE";
	(*g_pHelpStringTable)[HO_YOU_CANNOT_USE_SHIELD_WITH_CROSS] = "YOU_CANNOT_USE_SHIELD_WITH_CROSS";
	(*g_pHelpStringTable)[HO_YOU_CANNOT_USE_SHIELD_WITH_MACE] = "YOU_CANNOT_USE_SHIELD_WITH_MACE";
	(*g_pHelpStringTable)[HO_YOU_CANT_USE_SKILL_LACK_OF_MANA] = "YOU_CANT_USE_SKILL_LACK_OF_MANA";
	(*g_pHelpStringTable)[HO_YOU_CAN_DROP_MONEY_WITH_ICON_IN_INVENTORY] = "YOU_CAN_DROP_MONEY_WITH_ICON_IN_INVENTORY";
	(*g_pHelpStringTable)[HO_YOU_CAN_THROW_HOLY_WATER_WITH_SKILL_SELECT] = "YOU_CAN_THROW_HOLY_WATER_WITH_SKILL_SELECT";
	(*g_pHelpStringTable)[HO_YOU_CAN_USE_SHIELD_WITH_SWORD] = "YOU_CAN_USE_SHIELD_WITH_SWORD";
	(*g_pHelpStringTable)[HO_YOU_MORPH_TO_VAMPIRE_IN_12_HOURS] = "YOU_MORPH_TO_VAMPIRE_IN_12_HOURS";
	(*g_pHelpStringTable)[HO_YOU_MUST_REPAIR_ITEM_BEFORE_BROKEN] = "YOU_MUST_REPAIR_ITEM_BEFORE_BROKEN";
	(*g_pHelpStringTable)[HO_YOU_WILL_DIE_WHEN_HP_ZERO] = "YOU_WILL_DIE_WHEN_HP_ZERO";

	//-------------------------------------------------------
	// Save To File
	//-------------------------------------------------------
	std::ofstream file(g_pFileDef->getProperty("FILE_INFO_SMART_HELP_STRING").c_str(), std::ios::binary);

	g_pHelpStringTable->SaveToFile( file );

	file.close();

	return TRUE;
}
