//----------------------------------------------------------------------
// MTypeDef.h
//----------------------------------------------------------------------

#ifndef	__MTYPEDEF_H__
#define	__MTYPEDEF_H__

#pragma warning(disable:4786)

//------------------------------------------------------------------
// NULL값
//------------------------------------------------------------------
#define	ZONEID_NULL						0xFFFF
#define	OBJECTID_NULL					0xFFFFFFFF		// 아무것도 없다는 의미..
#define	INTERACTIONOBJECTTYPE_NULL		0xFFFF
#define	SECTORPOSITION_NULL				0xFFFF

#define	ITEMTYPE_NULL					0xFFFF
#define	ITEM_OPTION_NULL				0xFFFF
#define	ITEM_DURATION_NULL				0xFFFFFFFF
#define	ITEM_PRICE_NULL					0xFFFFFFFF
#define	ITEM_NUMBER_NULL				0xFFFFFFFF
#define	ITEM_WEIGHT_NULL				0xFFFF


//------------------------------------------------------------------
// sizeof( TYPE_... )
//------------------------------------------------------------------
#define	SIZE_OBJECTID					4
#define	SIZE_ZONEID						2
//#define	SIZE_ITEMCLASS					2
#define	SIZE_INTERACTIONOBJECTTYPE		2
#define	SIZE_SECTORPOSITION				2

#define	SIZE_ITEMTYPE					2
#define	SIZE_ITEM_OPTION				2
#define	SIZE_ITEM_DURATION				4
#define	SIZE_ITEM_PRICE					4
#define	SIZE_ITEM_NUMBER				4
#define	SIZE_ITEM_WEIGHT				2


//------------------------------------------------------------------
// typedef
//------------------------------------------------------------------
typedef	unsigned short	TYPE_ZONEID;
typedef	unsigned int	TYPE_OBJECTID;
//typedef	unsigned short	TYPE_ITEMCLASS;
typedef	unsigned short	TYPE_INTERACTIONOBJECTTYPE;
typedef	unsigned short	TYPE_SECTORPOSITION;

typedef	unsigned short	TYPE_ITEMTYPE;
typedef	unsigned short	TYPE_ITEM_OPTION;
typedef	unsigned int	TYPE_ITEM_DURATION;
//typedef	unsigned short	TYPE_ITEM_DURATION;
typedef	unsigned int	TYPE_ITEM_PRICE;
typedef	unsigned int	TYPE_ITEM_NUMBER;
typedef	unsigned short	TYPE_ITEM_WEIGHT;
typedef	unsigned char	TYPE_ITEM_OPTION_2;


//----------------------------------------------------------------------
//
//                 Creature 관련
//
//----------------------------------------------------------------------

#define	CREATURETYPE_NULL				0xFFFF

#define	SIZE_CREATURETYPE				2

typedef	unsigned short	TYPE_CREATURETYPE;

//----------------------------------------------------------------------
// 방향에 대한 값
//----------------------------------------------------------------------
enum DIRECTIONS
{			
	DIRECTION_LEFT = 0,
	DIRECTION_LEFTDOWN,
	DIRECTION_DOWN,
	DIRECTION_RIGHTDOWN,
	DIRECTION_RIGHT,
	DIRECTION_RIGHTUP,
	DIRECTION_UP,
	DIRECTION_LEFTUP,
	DIRECTION_MAX,	
	DIRECTION_NULL
};

#define	MAX_DIRECTION	DIRECTION_MAX

//----------------------------------------------------------------------
// 행동에 대한 값
//----------------------------------------------------------------------
// VAMPIRE와 SLAYER가 같은 값을 가지는 이유는
// FramePack에서의 Action번호 때문이다..
//

//////////////////////////////////////////////////////////////////////////
// Common Action
enum {
	ACTION_STAND,								// 0
	ACTION_MOVE,								// 1
	ACTION_ATTACK,								// 2
	ACTION_MAGIC,								// 3
	ACTION_DAMAGED,								// 4
	ACTION_DRAINED,								// 5	//구시온과 모르고스는 흡혈을 안한다. 다른 공격 스킬을 사용한다.
	ACTION_DIE,									// 6

	ACTION_MAX_COMMON,
};

//////////////////////////////////////////////////////////////////////////
// Slayer Action

// 2007.09.06 - Slayer Renewal
enum {
	ACTION_SLAYER_GUN_SR = ACTION_MAX_COMMON,	// 7			// 저격용(TR)
	ACTION_SLAYER_GUN_AR,						// 8			// 소총(AG)
	ACTION_SLAYER_GUN_SG,						// 9			// 샷건(SG)
	ACTION_SLAYER_GUN_SMG,						// 10			// 자동소총(SMG)

	ACTION_SLAYER_SWORD,						// 11			// 칼
	ACTION_SLAYER_BLADE,						// 12			// 도
	ACTION_SLAYER_SWORD_2,						// 13			// 칼 특수동작
	ACTION_SLAYER_BLADE_2,						// 14			// 도 특수동작

	ACTION_SLAYER_MOTOR_MOVE,					// 15
	ACTION_SLAYER_MOTOR_STAND,					// 16

	ACTION_SLAYER_GUN_SR_SLOW,					// 17			// 저격용(TR)
	ACTION_SLAYER_GUN_SR_FAST,					// 18			// 저격용(TR)
	ACTION_SLAYER_GUN_AR_SLOW,					// 19			// 소총(AG)
	ACTION_SLAYER_GUN_AR_FAST,					// 20	 		// 소총(AG)
	ACTION_SLAYER_GUN_SG_SLOW,					// 21			// 샷건(SG)
	ACTION_SLAYER_GUN_SG_FAST,					// 22			// 샷건(SG)
	ACTION_SLAYER_GUN_SMG_SLOW,					// 23			// 자동소총(SMG)
	ACTION_SLAYER_GUN_SMG_FAST,					// 24			// 자동소총(SMG)

	ACTION_SLAYER_SWORD_SLOW,					// 25			// 칼
	ACTION_SLAYER_SWORD_FAST,					// 26			// 칼
	ACTION_SLAYER_BLADE_SLOW,					// 27			// 도
	ACTION_SLAYER_BLADE_FAST,					// 28			// 도

	ACTION_SLAYER_SWORD_2_SLOW,					// 29			// 칼 특수동작
	ACTION_SLAYER_SWORD_2_FAST,					// 30			// 칼 특수동작
	ACTION_SLAYER_BLADE_2_SLOW,					// 31			// 도 특수동작
	ACTION_SLAYER_BLADE_2_FAST,					// 32			// 도 특수동작

	ACTION_SLAYER_BATTLE_STAND_GUN,				// 33
	ACTION_SLAYER_BATTLE_STAND_SWORD,			// 34
	ACTION_SLAYER_BATTLE_STAND_BLADE,			// 35

	ACTION_SLAYER_MOVE_GUN,						// 36

	ACTION_SLAYER_MAGIC_CASTING,				// 37
	
	ACTION_SLAYER_SWORD_2_REPEAT,				// 38
	ACTION_SLAYER_BLADE_2_REPEAT,				// 39

	ACTION_MAX_SLAYER,
};

//////////////////////////////////////////////////////////////////////////
// Vampire Action
enum {
	// 2001.6.5 추가된거
	ACTION_VAMPIRE_DRAIN = ACTION_MAX_COMMON,	// 7
	ACTION_VAMPIRE_ATTACK_SLOW,					// 8			// vampire전용
	ACTION_VAMPIRE_ATTACK_FAST,					// 9			// vampire전용

	// chyaya 2007.05.06 뱀파이어 공격 모션x2, 시전형 마법 모션 추가
	ACTION_VAMPIRE_ATTACK_2,					// 10
	ACTION_VAMPIRE_ATTACK_2_SLOW,				// 11
	ACTION_VAMPIRE_ATTACK_2_FAST,				// 12
	ACTION_VAMPIRE_ATTACK_3,					// 13
	ACTION_VAMPIRE_ATTACK_3_SLOW,				// 14
	ACTION_VAMPIRE_ATTACK_3_FAST,				// 15
	ACTION_VAMPIRE_MAGIC_CASTING,				// 16

	ACTION_MAX_VAMPIRE,
};

/*
// 2005.6.20 추가된거
#define	ACTION_VAMPIRE_SKILL_ATTACK				10			// vampire전용
#define	ACTION_VAMPIRE_SKILL_ATTACK_SLOW		11			// vampire전용
#define	ACTION_VAMPIRE_SKILL_ATTACK_FAST		12			// vampire전용
*/

// 2001.7.6
#define	ACTION_MONSTER_DIE_BODY		10			// Vampire Monster전용 - 머리없고 목만 있는 것


//////////////////////////////////////////////////////////////////////////
// Ousters Action
enum {
	ACTION_OUSTERS_STAND = ACTION_MAX_COMMON,	// 7			// 서있기
	ACTION_OUSTERS_MOVE,						// 8			// 걷기
	ACTION_OUSTERS_CHAKRAM,						// 9			// 차크람 공격
	ACTION_OUSTERS_MAGIC_ATTACK,				// 10			// 마법 공격
	ACTION_OUSTERS_DRAIN,						// 11			// 흡영
	ACTION_OUSTERS_FAST_MOVE_STAND,				// 12			// 공중 정지
	ACTION_OUSTERS_FAST_MOVE_MOVE,				// 13			// 공중 움직임
	ACTION_OUSTERS_ATTACK_SLOW,					// 14			// 일반 공격 느림
	ACTION_OUSTERS_ATTACK_FAST,					// 15			// 일반 공격 빠름
	ACTION_OUSTERS_CHAKRAM_SLOW,				// 16			// 차크람 공격 느림
	ACTION_OUSTERS_CHAKRAM_FAST,				// 17			// 차크람 공격 빠름
//#if __CONTENTS(__FAST_TRANSFORTER)
	ACTION_OUSTERS_WING_STAND,					// 18
	ACTION_OUSTERS_WING_MOVE,					// 19
//#endif //__FAST_TRANSFORTER
//#if __CONTENTS(__SECOND_TRANSFORTER)
	ACTION_OUSTERS_UNICORN_STAND,				// 20
	ACTION_OUSTERS_UNICORN_MOVE,				// 21
//#endif //__SECOND_TRANSFORTER
	ACTION_MAX_OUSTERS,							// 20
};


#define	ACTION_MAX_NPC	2
#define	ACTION_MAX		19



//----------------------------------------------------------------------
// Addon위치
// ADDON_NULL는 슬레일 때 어깨 값으로 이용된다 서버에서는 ADDON_MOTOR다음 enum값으로 선언이 되어 있으며 
// 어깨는 외형 변화 없이 색값만 변경된다. 정상적으로 추가하여 ADDON_MAX보다 작은 값으로 어깨를 추가하면 좋으나 
// 실질적으로 외형 적용이 없기도 하거니와 리소스 데이터를 건드려야 할 부분이 많을 것으로 판단 된다. 
// 차후에 슬레이어 리뉴얼이 있거나 addon파츠를 줄이거나 늘일때 등 큰 작업이 있을때 서버와 동기화를 맞추는 것이 좋을것으로 판단된다.
//----------------------------------------------------------------------
enum ADDON
{
	ADDON_HAIR,			// 머리
	ADDON_HELM,			// 모자
	ADDON_COAT,			// 상의
	ADDON_TROUSER,		// 하의
	//ADDON_SHOES,		// 신발
	//ADDON_LEFTGLOVE,		// 왼손 장갑
	//ADDON_RIGHTGLOVE,		// 오른손 장갑
	ADDON_LEFTHAND,		// 왼손			
	ADDON_RIGHTHAND,	// 오른손
	//ADDON_CLOAK,		// 외투
	ADDON_MOTOR,		// 오토바이
	ADDON_MAX,
	ADDON_NULL	= 0xFFFF,
};



//----------------------------------------------------------------------
//
//                          Effect 관련
//
//----------------------------------------------------------------------
#define	ACTIONINFO_NULL					0xFFFF
#define	SIZE_ACTIONINFO					2
typedef	unsigned short	TYPE_ACTIONINFO;


//----------------------------------------------------------------------
//
//                       EffectGenerator 관련
//
//----------------------------------------------------------------------
typedef	unsigned short TYPE_EFFECTGENERATORID;
#define	SIZE_EFFECTGENERATORID			2
#define	EFFECTGENERATORID_NULL			0xFFFF



//----------------------------------------------------------------------
//
//                       Sound / Music 관련
//
//----------------------------------------------------------------------

typedef unsigned short TYPE_SOUNDID;
#define	SIZE_SOUNDID	2
#define	SOUNDID_NULL	0xFFFF

typedef unsigned short TYPE_MUSICID;
#define	SIZE_MUSICID	2
#define	MUSICID_NULL	0xFFFF


//----------------------------------------------------------------------
// EffectSpriteType 정의
//----------------------------------------------------------------------
typedef	unsigned short				TYPE_EFFECTSPRITETYPE;
#define	SIZE_EFFECTSPRITETYPE		2
#define	EFFECTSPRITETYPE_NULL		0xFFFF


//----------------------------------------------------------------------
// link Count
//----------------------------------------------------------------------
#define	MAX_LINKCOUNT				0xFFFF

enum {
	ACTION_ADVANCEMENT_SLAYER_STOP_SWORD = 100,
	ACTION_ADVANCEMENT_SLAYER_STOP_BLADE,
	ACTION_ADVANCEMENT_SLAYER_STOP_GUN,
	ACTION_ADVANCEMENT_SLAYER_STOP_MACE_AND_CROSS,
	
	ACTION_ADVANCEMENT_SLAYER_MOVE_SWORD,
	ACTION_ADVANCEMENT_SLAYER_MOVE_BLADE,
	ACTION_ADVANCEMENT_SLAYER_MOVE_GUN,
	ACTION_ADVANCEMENT_SLAYER_MOVE_MACE_AND_CROSS,

	ACTION_ADVANCEMENT_SLAYER_ATTACK_SWORD_SLOW,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_SWORD_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_SWORD_FAST,
	
	ACTION_ADVANCEMENT_SLAYER_ATTACK_BLADE_SLOW,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_BLADE_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_BLADE_FAST,
	
	ACTION_ADVANCEMENT_SLAYER_ATTACK_AR_GUN_SLOW,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_AR_GUN_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_AR_GUN_FAST,
	
	ACTION_ADVANCEMENT_SLAYER_ATTACK_SR_GUN_SLOW,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_SR_GUN_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_ATTACK_SR_GUN_FAST,

	ACTION_ADVANCEMENT_SLAYER_SKILL_SWORD_SLOW,
	ACTION_ADVANCEMENT_SLAYER_SKILL_SWORD_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_SKILL_SWORD_FAST,

	ACTION_ADVANCEMENT_SLAYER_SKILL_BLADE_SLOW,
	ACTION_ADVANCEMENT_SLAYER_SKILL_BLADE_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_SKILL_BLADE_FAST,

	ACTION_ADVANCEMENT_SLAYER_SKILL_GUN_SLOW,
	ACTION_ADVANCEMENT_SLAYER_SKILL_GUN_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_SKILL_GUN_FAST,
	
	ACTION_ADVANCEMENT_SLAYER_MAGIC,
	ACTION_ADVANCEMENT_SLAYER_MAGIC_ATTACK,

	ACTION_ADVANCEMENT_SLAYER_DRAINED,
	ACTION_ADVANCEMENT_SLAYER_DAMAGED_SWORD,
	ACTION_ADVANCEMENT_SLAYER_DAMAGED_BLADE,
	ACTION_ADVANCEMENT_SLAYER_DAMAGED_GUN,
	ACTION_ADVANCEMENT_SLAYER_DAMAGED_CROSS_MACE,
	ACTION_ADVANCEMENT_SLAYER_DIE,

	ACTION_ADVANCEMENT_SLAYER_BIKE_MOVE,
	ACTION_ADVANCEMENT_SLAYER_BIKE_STOP,

	ACTION_ADVANCEMENT_SLAYER_SPECIAL,
	ACTION_ADVANCEMENT_SLAYER_SPECIAL_2,
	
	ACTION_ADVANCEMENT_SLAYER_SLIDING,
	ACTION_ADVANCEMENT_SLAYER_SLIDING_END,

	/*ACTION_ADVANCEMENT_SLAYER_SWORD_SLIDING,
	ACTION_ADVANCEMENT_SLAYER_SWORD_SLIDING_END,

	ACTION_ADVANCEMENT_SLAYER_BLADE_SLIDING,
	ACTION_ADVANCEMENT_SLAYER_BLADE_SLIDING_END,

	// 2005.06.09 sjheon  Combo Action Add

	ACTION_ADVANCEMENT_SLAYER_COMBO_SWARD_SLOW ,
	ACTION_ADVANCEMENT_SLAYER_COMBO_SWARD_NORMAL ,
	ACTION_ADVANCEMENT_SLAYER_COMBO_SWARD_FAST ,
	
	ACTION_ADVANCEMENT_SLAYER_COMBO_BLADE_SLOW ,
	ACTION_ADVANCEMENT_SLAYER_COMBO_BLADE_NORMAL ,
	ACTION_ADVANCEMENT_SLAYER_COMBO_BLADE_FAST ,

	ACTION_ADVANCEMENT_SLAYER_COMBO_CANCEL_SWARD_SLOW,
	ACTION_ADVANCEMENT_SLAYER_COMBO_CANCEL_SWARD_NORMAL,
	ACTION_ADVANCEMENT_SLAYERN_COMBO_CANCEL_SWARD_FAST,

	ACTION_ADVANCEMENT_SLAYER_COMBO_CANCEL_BLADE_SLOW,
	ACTION_ADVANCEMENT_SLAYER_COMBO_CANCEL_BLADE_NORMAL,
	ACTION_ADVANCEMENT_SLAYER_COMBO_CANCEL_BLADE_FAST,*/

	// 2005.06.09 sjheon  Combo Action End
	ACTION_ADVANCEMENT_SLAYER_MAX,
};

enum
{
	ACTION_ADVANCEMENT_OUSTERS_CHAKRAM_STOP = 100,	//0
	ACTION_ADVANCEMENT_OUSTERS_CHAKRAM_MOVE,		//1
	ACTION_ADVANCEMENT_OUSTERS_WRISTLET_STOP,		//2
	ACTION_ADVANCEMENT_OUSTERS_WRISTLET_MOVE,		//3

	ACTION_ADVANCEMENT_OUSTERS_ATTACK_SLOW,			//4
	ACTION_ADVANCEMENT_OUSTERS_ATTACK_NORMAL,		//5
	ACTION_ADVANCEMENT_OUSTERS_ATTACK_FAST,			//6
	ACTION_ADVANCEMENT_OUSTERS_SKILL_SLOW,			//7
	ACTION_ADVANCEMENT_OUSTERS_SKILL_NORMAL,		//8
	ACTION_ADVANCEMENT_OUSTERS_SKILL_FAST,			//9

	ACTION_ADVANCEMENT_OUSTERS_MAGIC_ATTACK,		//10

	ACTION_ADVANCEMENT_OUSTERS_MAGIC,				//11
	ACTION_ADVANCEMENT_OUSTERS_ABSORB_SOUL,			//12
	ACTION_ADVANCEMENT_OUSTERS_DRAINED,				//13
	ACTION_ADVANCEMENT_OUSTERS_DIE,					//14
	ACTION_ADVANCEMENT_OUSTERS_DAMAGED,				//15
	ACTION_ADVANCEMENT_OUSTERS_SPECIAL,				//16

	ACTION_ADVANCEMENT_OUSTERS_FAST_MOVE_STOP,		//17
	ACTION_ADVANCEMENT_OUSTERS_FAST_MOVE,			//18

#if __CONTENTS(__FAST_TRANSFORTER)
	ACTION_ADVANCEMENT_OUSTERS_WING_MOVE,			//19
	ACTION_ADVANCEMENT_OUSTERS_WING_STOP,			//20
#endif //__FAST_TRANSFORTER
#if __CONTENTS(__SECOND_TRANSFORTER)
	ACTION_ADVANCEMENT_OUSTERS_UNICORN_MOVE,		//21
	ACTION_ADVANCEMENT_OUSTERS_UNICORN_STOP,		//22
#endif //__SECOND_TRANSFORTER

	// 2005.06.09 sjheon  Combo Action Add
	/*ACTION_ADVANCEMENT_OUSTERS_SLIDING,
	ACTION_ADVANCEMENT_OUSTERS_SLIDING_END,
	
	ACTION_ADVANCEMENT_OUSTERS_COMBO_SLOW,
	ACTION_ADVANCEMENT_OUSTERS_COMBO_NORMAL,
	ACTION_ADVANCEMENT_OUSTERS_COMBO_FAST,
		
	ACTION_ADVANCEMENT_OUSTERS_COMBO_CANCEL_SLOW,
	ACTION_ADVANCEMENT_OUSTERS_COMBO_CANCEL_NORMAL,
	ACTION_ADVANCEMENT_OUSTERS_COMBO_CANCEL_FAST,*/
	// 2005.06.09 sjheon  Combo Action End

	ACTION_ADVANCEMENT_OUSTERS_MAX
};

enum {
	ACTION_ADVANCEMENT_STOP = 100,
	ACTION_ADVANCEMENT_MOVE,
	ACTION_ADVANCEMENT_DAMAGED,
	ACTION_ADVANCEMENT_DIE,
	ACTION_ADVANCEMENT_DRAIN,
	ACTION_ADVANCEMENT_DRAINED,

	ACTION_ADVANCEMENT_ATTACK_SLOW,
	ACTION_ADVANCEMENT_ATTACK_NORMAL,
	ACTION_ADVANCEMENT_ATTACK_FAST,

	ACTION_ADVANCEMENT_SKILL_SLOW,
	ACTION_ADVANCEMENT_SKILL_NORMAL,
	ACTION_ADVANCEMENT_SKILL_FAST,

	ACTION_ADVANCEMENT_MAGIC,
	ACTION_ADVANCEMENT_MAGIC_ATTACK,
	ACTION_ADVANCEMENT_SPECIAL,
	ACTION_ADVANCEMENT_CREATE_WEAPON,
	ACTION_ADVANCEMENT_DESTROY_WEAPON,

	// 2005.06.09 sjheon  Combo Action Add
	/*ACTION_ADVANCEMENT_SLIDING,
	ACTION_ADVANCEMENT_SLIDING_END,
	
	ACTION_ADVANCEMENT_COMBO_SLOW,
	ACTION_ADVANCEMENT_COMBO_NORMAL,
	ACTION_ADVANCEMENT_COMBO_FAST,

	ACTION_ADVANCEMENT_COMBO_CANCEL_SLOW,
	ACTION_ADVANCEMENT_COMBO_CANCEL_NORMAL,
	ACTION_ADVANCEMENT_COMBO_CANCEL_FAST,*/
	// 2005.06.09 sjheon  Combo Action End
	
	ACTION_ADVANCEMENT_MAX,
};

enum AC_SLAYER_PART
{
	AC_BODY = 0,
	AC_HELMET,
	AC_SWORD,
	AC_BLADE,
	AC_CROSS,
	AC_MACE,
	AC_GUN_AR,
	AC_GUN_SR,
	AC_SHIELD,
	AC_BIKE_1,
	AC_BIKE_2,
	AC_SHOULDER,
	AC_BIKE_2_COLOR,
#if __CONTENTS(__FAST_TRANSFORTER)
	AC_WING_BIKE,
#endif //__FAST_TRANSFORTER
#if __CONTENTS(__SECOND_TRANSFORTER)
	AC_HOVER_VEHICLE,
#endif //__SECOND_TRANSFORTER
	AC_AIR_MOTO,
	AC_APQ,
	AC_PART_MAX,
};

enum ADVANCEMENT201_SLAYER_PART
{
	ADVANCEMENT201_SWORD_1,	//0
	ADVANCEMENT201_SWORD_2,	//1
	ADVANCEMENT201_BLADE_1,	//2
	ADVANCEMENT201_BLADE_2,	//3
	ADVANCEMENT201_GUN_SR_1,	//4
	ADVANCEMENT201_GUN_SR_2,	//5
	ADVANCEMENT201_GUN_AR_1,	//6
	ADVANCEMENT201_GUN_AR_2,	//7
	ADVANCEMENT201_CROSS_1,	//8
	ADVANCEMENT201_CROSS_2,	//9
	ADVANCEMENT201_MACE_1,	//10
	ADVANCEMENT201_MACE_2,	//11
	ADVANCEMENT201_SHIELD_1,	//12
	ADVANCEMENT201_SHIELD_2,	//13
	ADVANCEMENT201_HELMET_1,	//14
	UNKOWN201_1,				//15
	UNKOWN201_2,				//16
	ADVANCEMENT201_SHOULDER_1,	//17
	ADVANCEMENT201_SHOULDER_2,	//18
	ADVANCEMENT201_COAT_1,		//19
	ADVANCEMENT201_COAT_2,		//20
	ADVANCEMENT201_TROUSER_1,		//21
	ADVANCEMENT201_TROUSER_2,		//22
	ADVANCEMENT201_WING_BIKE,		//23
	ADVANCEMENT201_HOVER_VEHICLE,		//24
	ADVANCEMENT201_AIR_MOTO,
};

enum ADVANCEMENT_SLAYER_PART
{
	ADVANCEMENT_SWORD_1,	//0
	ADVANCEMENT_SWORD_2,	//1
	ADVANCEMENT_BLADE_1,	//2
	ADVANCEMENT_BLADE_2,	//3
	ADVANCEMENT_GUN_SR_1,	//4
	ADVANCEMENT_GUN_SR_2,	//5
	ADVANCEMENT_GUN_AR_1,	//6
	ADVANCEMENT_GUN_AR_2,	//7
	ADVANCEMENT_CROSS_1,	//8
	ADVANCEMENT_CROSS_2,	//9
	ADVANCEMENT_MACE_1,	//10
	ADVANCEMENT_MACE_2,	//11
	ADVANCEMENT_SHIELD_1,	//12
	ADVANCEMENT_SHIELD_2,	//13
	ADVANCEMENT_HELMET_1,	//14
	UNKOWN_1,				//15
	UNKOWN_2,				//16
	ADVANCEMENT_SHOULDER_1,	//17
	ADVANCEMENT_SHOULDER_2,	//18
	ADVANCEMENT_COAT_1,		//19
	ADVANCEMENT_COAT_2,		//20
	ADVANCEMENT_TROUSER_1,		//21
	ADVANCEMENT_TROUSER_2,		//22
	ADVANCEMENT_WING_BIKE,		//23
	ADVANCEMENT_HOVER_VEHICLE,		//24
	ADVANCEMENT_AIR_MOTO,
	ADVANCEMENT_APQ_VEHICLE,
};
enum AC_ADDON
{
	AC_ADDON_BODY,		// 몸통
	AC_ADDON_HELM,		// 헬멧
	AC_ADDON_LEFTHAND,	// 왼손
	AC_ADDON_RIGHTHAND,	// 오른손
	AC_ADDON_MOTOR,		// 오토바이
	AC_ADDON_SHOULDER,	// 견장
	AC_ADDON_MAX,
	AC_ADDON_NULL	= 0xFFFF,
};

#define ADVANCEMENT_ACTION_START	100

#endif
