//IOCTL.h
#define	FILE_DRIVER_SSDT	0x0000420

#define	DRIVER_NAME		L"\\Device\\VVPROTECT"
#define	DEVICE_NAME		L"\\DosDevices\\VVPROTECT"

#ifndef CTL_CODE
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)
#endif // CTL_CODE

#define FILE_DEVICE_GAMEDRV  0x00272130
#define GAMEDRV_IOCTL_INDEX  0x217

#ifndef METHOD_NEITHER
#define METHOD_NEITHER 3
#endif // METHOD_NEITHER
/*
////////////////////////////////////////////////////////////////////
//ZwDebugActiveProcess
#define IOCTL_HOOK_ZWDEBUGACTIVEPROCESS  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x01, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )
#define IOCTL_UNHOOK_ZWDEBUGACTIVEPROCESS  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x02, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )

//ZwSetInformation
#define IOCTL_HOOK_ZWSETINFORMATIONTHREAD  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x03, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )
#define IOCTL_UNHOOK_ZWSETINFORMATIONTHREAD  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x04, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )

//ZwQuerySystemInformation
#define IOCTL_HOOK_ZWQUERYSYSTEMINFORMATION  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x05, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )
#define IOCTL_UNHOOK_ZWQUERYSYSTEMINFORMATION  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x06, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )

//ZwMapViewOfSection
#define IOCTL_HOOK_ZWMAPVIEWOFSECTION  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x07, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )
#define IOCTL_UNHOOK_ZWMAPVIEWOFSECTION  (ULONG)CTL_CODE( FILE_DRIVER_SSDT, 0x08, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA )
*/
/*
#define GM_SET_PID      CTL_CODE(FILE_DEVICE_GAMEDRV,GAMEDRV_IOCTL_INDEX,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define GM_GET_PID      CTL_CODE(FILE_DEVICE_GAMEDRV,GAMEDRV_IOCTL_INDEX+1,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define GM_START		CTL_CODE(FILE_DEVICE_GAMEDRV,GAMEDRV_IOCTL_INDEX+2,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define GM_STOP			CTL_CODE(FILE_DEVICE_GAMEDRV,GAMEDRV_IOCTL_INDEX+3,METHOD_BUFFERED,FILE_ANY_ACCESS)
*/

#define GM_SET_PID      CTL_CODE(FILE_DEVICE_GAMEDRV, GAMEDRV_IOCTL_INDEX,   METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define GM_GET_PID      CTL_CODE(FILE_DEVICE_GAMEDRV, GAMEDRV_IOCTL_INDEX+1, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define GM_START		CTL_CODE(FILE_DEVICE_GAMEDRV, GAMEDRV_IOCTL_INDEX+2, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define GM_STOP			CTL_CODE(FILE_DEVICE_GAMEDRV, GAMEDRV_IOCTL_INDEX+3, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define GM_CHECK		CTL_CODE(FILE_DEVICE_GAMEDRV, GAMEDRV_IOCTL_INDEX+4, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)


typedef struct _GM_PID_PARAM
{
	ULONG ulProcessId;
//	PVOID ReadParamAddress;
	ULONG ulGameProcessId;
}GM_PID_PARAM,*PGM_PID_PARAM;