//----------------------------------------------------------------------
// AcceleratorDef.h
//----------------------------------------------------------------------

#ifndef __ACCELERATOR_H__
#define __ACCELERATOR_H__

#if __CONTENTS(__080405_FIREST_UI_UPDATE)
#define MAX_ACCELERATOR_NAME_TYPE 2
#endif //__080405_FIREST_UI_UPDATE

enum ACCELERATOR 
{
	ACCEL_NULL,
	ACCEL_F1,
	ACCEL_F2,
	ACCEL_F3,
	ACCEL_F4,
	ACCEL_F5,
	ACCEL_F6,
	ACCEL_F7,
	ACCEL_F8,
	ACCEL_F9,
	ACCEL_F10,
	ACCEL_F11,
	ACCEL_F12,
	ACCEL_ESC,
	ACCEL_SKILL,
	ACCEL_INVENTORY,
	ACCEL_GEAR,
	ACCEL_CHARINFO,
	ACCEL_SKILLINFO,
	ACCEL_GRADE1INFO,
	ACCEL_WORLDMAP,
	ACCEL_PARTY,
	ACCEL_HELP,
	ACCEL_QUICKITEM_SLOT,
	ACCEL_EXTEND_CHAT,
	ACCEL_CHAT,
	ACCEL_CHAT_DN,
	ACCEL_NORMALCHAT,
	ACCEL_ZONECHAT,
	ACCEL_WHISPER,
	ACCEL_PARTYCHAT,
	ACCEL_GUILD,
	ACCEL_UNION,
	ACCEL_QUEST,	
	ACCEL_MAILBOX,
	ACCEL_PETINFO,

//	// 2004, 5, 17 sobeit add start
	ACCEL_SUMMON_PET,
//	// 2004, 5, 17 sobeit add end
	ACCEL_TRIBE_PRIOR,
	ACCEL_TRIBE_NEXT,
//	ACCEL_GUILD_INFO,
//	ACCEL_GUILD_MEMBER_LIST,
	ACCEL_COER_ATTACK,
// by svi
	ACCEL_AUTO_ATTACK,
// end
	ACCEL_SYSRQ,
	ACCEL_MINIMAP,
//	ACCEL_SLASH,

#if __CONTENTS(__GEAR_SWAP_CHANGE)	// 장착창 교체키 인덱스 선언
	ACCEL_GEAR_CHANGE,
	ACCEL_GEAR_CHANGE_SHOW,
#endif // __GEAR_SWAP_CHANGE

	MAX_ACCELERATOR
};

#if __CONTENTS(__080405_FIREST_UI_UPDATE)
extern const char* ACCELERATOR_NAME[MAX_ACCELERATOR][MAX_ACCELERATOR_NAME_TYPE];
#else
extern const char* ACCELERATOR_NAME[MAX_ACCELERATOR];		
#endif //__080405_FIREST_UI_UPDATE

extern void	SetDefaultAccelerator();

#endif